const { connectDatabase } = require("../config/db");
const Question = require("../models/Question");
const Course = require("../models/Course");
const College = require("../models/College");
const Deadline = require("../models/Deadline");
const Resource = require("../models/Resource");
const RoadmapNode = require("../models/RoadmapNode");
const RoadmapEdge = require("../models/RoadmapEdge");

const obsoleteCollegeSlugs = [
  "skyline-institute-of-technology",
  "riverdale-commerce-management-college",
  "harmony-school-of-humanities",
  "craftbridge-vocational-academy",
];

const sampleQuestions = [
  {
    order: 1,
    category: "science",
    question: "Do you enjoy mathematics and numerical problem solving?",
    options: [
      { label: "Very much", value: "math-high", weights: { science: 5, commerce: 3, arts: 0, vocational: 1 } },
      { label: "Somewhat", value: "math-medium", weights: { science: 3, commerce: 2, arts: 1, vocational: 1 } },
      { label: "Not really", value: "math-low", weights: { science: 0, commerce: 1, arts: 2, vocational: 2 } },
    ],
  },
  {
    order: 2,
    category: "creativity",
    question: "Do you like designing things, visuals, or user experiences?",
    options: [
      { label: "Yes, a lot", value: "design-high", weights: { science: 1, commerce: 1, arts: 4, vocational: 5 } },
      { label: "A little", value: "design-medium", weights: { science: 1, commerce: 1, arts: 3, vocational: 3 } },
      { label: "Not much", value: "design-low", weights: { science: 3, commerce: 3, arts: 0, vocational: 1 } },
    ],
  },
  {
    order: 3,
    category: "social",
    question: "Do you enjoy helping people through guidance, healthcare, or communication?",
    options: [
      { label: "Yes", value: "people-high", weights: { science: 3, commerce: 1, arts: 5, vocational: 2 } },
      { label: "Sometimes", value: "people-medium", weights: { science: 2, commerce: 1, arts: 3, vocational: 2 } },
      { label: "Rarely", value: "people-low", weights: { science: 2, commerce: 3, arts: 1, vocational: 2 } },
    ],
  },
  {
    order: 4,
    category: "logic",
    question: "Do you like computers, software, or technology-driven work?",
    options: [
      { label: "Yes, strongly", value: "tech-high", weights: { science: 5, commerce: 2, arts: 0, vocational: 2 } },
      { label: "Somewhat", value: "tech-medium", weights: { science: 3, commerce: 2, arts: 1, vocational: 2 } },
      { label: "Not really", value: "tech-low", weights: { science: 0, commerce: 2, arts: 2, vocational: 1 } },
    ],
  },
  {
    order: 5,
    category: "practical",
    question: "Do you prefer office-based work or field / hands-on work?",
    options: [
      { label: "Mostly office-based", value: "office", weights: { science: 2, commerce: 4, arts: 2, vocational: 1 } },
      { label: "A mix of both", value: "mixed", weights: { science: 3, commerce: 2, arts: 2, vocational: 3 } },
      { label: "Mostly field or hands-on", value: "field", weights: { science: 2, commerce: 1, arts: 1, vocational: 5 } },
    ],
  },
  {
    order: 6,
    category: "commerce",
    question: "Which future sounds most exciting to you right now?",
    options: [
      { label: "Engineer, software professional, or researcher", value: "future-tech", weights: { science: 5, commerce: 1, arts: 0, vocational: 1 } },
      { label: "Business leader, analyst, or finance expert", value: "future-business", weights: { science: 1, commerce: 5, arts: 0, vocational: 1 } },
      { label: "Law, media, psychology, or civil services", value: "future-arts", weights: { science: 0, commerce: 1, arts: 5, vocational: 1 } },
      { label: "Design, hospitality, or technical skilled work", value: "future-vocational", weights: { science: 1, commerce: 1, arts: 1, vocational: 5 } },
    ],
  },
];

const sampleCourses = [
  {
    name: "B.Tech Computer Science and Engineering",
    slug: "btech-cse",
    level: "Undergraduate",
    duration: "4 years",
    eligibleStreams: ["Science"],
    overview: "Covers programming, algorithms, AI foundations, databases, and software systems.",
    subjects: ["Programming", "Data Structures", "Databases", "Operating Systems", "AI Basics"],
    careerOutcomes: ["Software Engineer", "Data Scientist", "AI Engineer"],
    exams: ["JEE Main", "JEE Advanced", "MHT-CET"],
    higherStudies: ["M.Tech", "MS", "MBA"],
    skillsLearned: ["Programming", "Problem Solving", "System Design", "Debugging"],
    studyMaterials: [{ title: "Programming Foundations", type: "Roadmap", link: "https://roadmap.sh/", language: "English" }],
  },
  {
    name: "BCA",
    slug: "bca",
    level: "Undergraduate",
    duration: "3 years",
    eligibleStreams: ["Science", "Commerce", "Arts"],
    overview: "Build software and application development fundamentals with a practical computing focus.",
    subjects: ["Programming", "Web Development", "Databases", "Computer Networks"],
    careerOutcomes: ["Software Developer", "QA Engineer", "Web Developer"],
    exams: ["CUET UG", "University Entrance"],
    higherStudies: ["MCA", "M.Sc IT", "MBA"],
    skillsLearned: ["Coding", "Testing", "Web Development", "Database Design"],
    studyMaterials: [{ title: "App Development Starter", type: "Guide", link: "https://developer.mozilla.org/", language: "English" }],
  },
  {
    name: "B.Sc Computer Science",
    slug: "bsc-computer-science",
    level: "Undergraduate",
    duration: "3 years",
    eligibleStreams: ["Science"],
    overview: "A theory-plus-practice path for computing, analytics, and research-oriented learners.",
    subjects: ["Programming", "Algorithms", "Statistics", "Operating Systems"],
    careerOutcomes: ["Research Assistant", "Data Analyst", "Software Developer"],
    exams: ["CUET UG", "State CET"],
    higherStudies: ["M.Sc Computer Science", "MCA", "PhD"],
    skillsLearned: ["Coding", "Analytical Thinking", "Research Methods", "Database Design"],
    studyMaterials: [{ title: "CS Foundations", type: "Guide", link: "https://ocw.mit.edu/", language: "English" }],
  },
  {
    name: "B.Com",
    slug: "bcom",
    level: "Undergraduate",
    duration: "3 years",
    eligibleStreams: ["Commerce", "Arts"],
    overview: "Covers accounting, taxation, economics, business law, and financial reporting.",
    subjects: ["Accountancy", "Economics", "Taxation", "Business Law"],
    careerOutcomes: ["Accountant", "Financial Analyst", "Auditor"],
    exams: ["CUET UG"],
    higherStudies: ["M.Com", "MBA", "CA"],
    skillsLearned: ["Bookkeeping", "Financial Analysis", "Excel", "Business Communication"],
    studyMaterials: [{ title: "Finance Essentials", type: "Guide", link: "https://www.investopedia.com/", language: "English" }],
  },
  {
    name: "BBA",
    slug: "bba",
    level: "Undergraduate",
    duration: "3 years",
    eligibleStreams: ["Commerce", "Science", "Arts"],
    overview: "Focuses on management, marketing, entrepreneurship, and business analytics.",
    subjects: ["Management", "Marketing", "HR", "Business Analytics"],
    careerOutcomes: ["Business Analyst", "Management Trainee", "Sales Manager"],
    exams: ["CUET UG", "IPMAT"],
    higherStudies: ["MBA", "PGDM"],
    skillsLearned: ["Leadership", "Presentation", "Business Thinking", "Teamwork"],
    studyMaterials: [{ title: "Business Starter Pack", type: "Podcast", link: "https://open.spotify.com/", language: "English" }],
  },
  {
    name: "Chartered Accountancy Path",
    slug: "chartered-accountancy",
    level: "Professional",
    duration: "4.5 years",
    eligibleStreams: ["Commerce", "Arts"],
    overview: "A professional path through CA Foundation, Intermediate, articleship, and Final.",
    subjects: ["Accounting", "Taxation", "Audit", "Corporate Law"],
    careerOutcomes: ["Chartered Accountant", "Tax Consultant", "Finance Manager"],
    exams: ["CA Foundation", "CA Intermediate", "CA Final"],
    higherStudies: ["CPA", "MBA Finance"],
    skillsLearned: ["Accounting", "Audit", "Tax Planning", "Compliance"],
    studyMaterials: [{ title: "CA Path Overview", type: "Guide", link: "https://www.icai.org/", language: "English" }],
  },
  {
    name: "BA Psychology",
    slug: "ba-psychology",
    level: "Undergraduate",
    duration: "3 years",
    eligibleStreams: ["Arts", "Science"],
    overview: "Introduces human behavior, counseling basics, research methods, and cognition.",
    subjects: ["Psychology", "Research Methods", "Counseling", "Statistics"],
    careerOutcomes: ["Counselor", "HR Executive", "Behavioral Research Assistant"],
    exams: ["CUET UG"],
    higherStudies: ["MA Psychology", "MSW"],
    skillsLearned: ["Empathy", "Observation", "Research", "Interviewing"],
    studyMaterials: [{ title: "Mental Wellness Primer", type: "Article", link: "https://www.apa.org/", language: "English" }],
  },
  {
    name: "BA Journalism and Mass Communication",
    slug: "ba-journalism-mass-communication",
    level: "Undergraduate",
    duration: "3 years",
    eligibleStreams: ["Arts", "Commerce"],
    overview: "Builds reporting, media research, editing, and digital storytelling skills.",
    subjects: ["News Writing", "Digital Media", "Broadcasting", "Media Ethics"],
    careerOutcomes: ["Journalist", "Content Strategist", "PR Executive"],
    exams: ["CUET UG"],
    higherStudies: ["MA Mass Communication", "MBA Media Management"],
    skillsLearned: ["Storytelling", "Interviewing", "Editing", "Media Research"],
    studyMaterials: [{ title: "Writing for Media", type: "Course", link: "https://www.coursera.org/", language: "English" }],
  },
  {
    name: "LLB",
    slug: "llb",
    level: "Undergraduate / Professional",
    duration: "3 years",
    eligibleStreams: ["Arts", "Commerce", "Science"],
    overview: "Builds legal reasoning, constitutional understanding, and advocacy fundamentals.",
    subjects: ["Constitutional Law", "Criminal Law", "Contract Law", "Legal Research"],
    careerOutcomes: ["Lawyer", "Legal Analyst", "Judicial Services Aspirant"],
    exams: ["CLAT", "University Entrance"],
    higherStudies: ["LLM", "Judicial Services"],
    skillsLearned: ["Legal Reasoning", "Research", "Communication", "Argumentation"],
    studyMaterials: [{ title: "Legal Foundations", type: "Guide", link: "https://legalaffairs.gov.in/", language: "English" }],
  },
  {
    name: "MBBS",
    slug: "mbbs",
    level: "Undergraduate / Professional",
    duration: "5.5 years",
    eligibleStreams: ["Science"],
    overview: "The primary medical path for diagnosis, clinical care, and hospital practice.",
    subjects: ["Anatomy", "Physiology", "Biochemistry", "Clinical Rotations"],
    careerOutcomes: ["Doctor", "Medical Officer", "Clinical Specialist"],
    exams: ["NEET UG"],
    higherStudies: ["MD", "MS", "DNB"],
    skillsLearned: ["Clinical Observation", "Patient Care", "Medical Ethics", "Decision Making"],
    studyMaterials: [{ title: "Medical Entrance Prep", type: "Guide", link: "https://www.nmc.org.in/", language: "English" }],
  },
  {
    name: "B.Sc Nursing",
    slug: "bsc-nursing",
    level: "Undergraduate",
    duration: "4 years",
    eligibleStreams: ["Science"],
    overview: "Prepares students for nursing care, hospital systems, and patient management.",
    subjects: ["Nursing Foundations", "Anatomy", "Community Health", "Clinical Practice"],
    careerOutcomes: ["Nurse", "Clinical Coordinator", "Public Health Nurse"],
    exams: ["NEET UG", "Institute Entrance"],
    higherStudies: ["M.Sc Nursing", "Hospital Administration"],
    skillsLearned: ["Patient Care", "Observation", "Coordination", "Documentation"],
    studyMaterials: [{ title: "Nursing Pathway Guide", type: "Guide", link: "https://www.indiannursingcouncil.org/", language: "English" }],
  },
  {
    name: "Diploma in Graphic Design",
    slug: "diploma-graphic-design",
    level: "Diploma",
    duration: "1 year",
    eligibleStreams: ["Vocational", "Arts", "Commerce"],
    overview: "A design-focused diploma for branding, visual systems, and digital creatives.",
    subjects: ["Typography", "Branding", "Illustration", "Layout Design"],
    careerOutcomes: ["Graphic Designer", "UI UX Designer", "Brand Designer"],
    exams: ["Institute-specific admission"],
    higherStudies: ["B.Des", "Advanced Design Diploma"],
    skillsLearned: ["Adobe Tools", "Design Thinking", "Visual Communication"],
    studyMaterials: [{ title: "Design Inspiration", type: "Gallery", link: "https://www.behance.net/", language: "English" }],
  },
  {
    name: "Diploma in Hotel Management",
    slug: "diploma-hotel-management",
    level: "Diploma",
    duration: "1.5 years",
    eligibleStreams: ["Vocational", "Arts", "Commerce"],
    overview: "Develops hospitality operations, food service, and guest relations skills.",
    subjects: ["Hospitality Basics", "Front Office", "Food Production", "Service Skills"],
    careerOutcomes: ["Hotel Manager", "Guest Relations Associate", "Restaurant Supervisor"],
    exams: ["NCHMCT JEE", "Institute-specific admission"],
    higherStudies: ["BHM", "MBA Hospitality"],
    skillsLearned: ["Communication", "Service Operations", "Team Coordination"],
    studyMaterials: [{ title: "Hospitality Skills", type: "Video", link: "https://www.youtube.com/", language: "English" }],
  },
  {
    name: "Bachelor of Dental Surgery (BDS)",
    slug: "bds",
    level: "Undergraduate / Professional",
    duration: "5 years",
    eligibleStreams: ["Science"],
    overview: "Covers oral health, dental surgery, diagnosis, and care.",
    subjects: ["Anatomy", "Dental Materials", "Oral Pathology", "Clinical Practice"],
    careerOutcomes: ["Dentist", "Dental Surgeon"],
    exams: ["NEET UG"],
    higherStudies: ["MDS"],
    skillsLearned: ["Dental Surgery", "Patient Care", "Precision"],
    studyMaterials: [{ title: "Dental Anatomy Intro", type: "Guide", link: "https://www.dciindia.gov.in/", language: "English" }],
  },
  {
    name: "Bachelor of Pharmacy (B.Pharm)",
    slug: "bpharm",
    level: "Undergraduate",
    duration: "4 years",
    eligibleStreams: ["Science"],
    overview: "Covers drug formulation, pharmacology, clinical pharmacy, and pharmaceutical chemistry.",
    subjects: ["Pharmacology", "Pharmaceutics", "Pharmaceutical Chemistry", "Pharmacognosy"],
    careerOutcomes: ["Pharmacist", "Drug Inspector", "Chemical Analyst"],
    exams: ["NEET UG", "MHT-CET", "State CET"],
    higherStudies: ["M.Pharm", "MBA Pharma"],
    skillsLearned: ["Drug Formulation", "Chemical Analysis", "Clinical Research"],
    studyMaterials: [{ title: "Pharmacy Practice Guide", type: "Guide", link: "https://www.pci.nic.in/", language: "English" }],
  },
  {
    name: "Bachelor of Architecture (B.Arch)",
    slug: "barch",
    level: "Undergraduate",
    duration: "5 years",
    eligibleStreams: ["Science"],
    overview: "Covers architectural design, building construction, planning, and structural systems.",
    subjects: ["Architectural Design", "Building Construction", "Theory of Structures", "Urban Planning"],
    careerOutcomes: ["Architect", "Urban Planner", "Interior Designer"],
    exams: ["NATA", "JEE Main Paper 2"],
    higherStudies: ["M.Arch", "Master of Design"],
    skillsLearned: ["CAD Drawing", "Structural Planning", "Visual Design", "Spatial Thinking"],
    studyMaterials: [{ title: "Architecture Design Principles", type: "Guide", link: "https://www.coa.gov.in/", language: "English" }],
  },
  {
    name: "Diploma in Paramedical Technology",
    slug: "paramedical-diploma",
    level: "Diploma",
    duration: "2 years",
    eligibleStreams: ["Science", "Vocational"],
    overview: "Covers laboratory techniques, radiology, emergency medical care, and clinical support.",
    subjects: ["Clinical Biochemistry", "Radiology Basics", "Hematology", "Emergency Care"],
    careerOutcomes: ["Lab Technician", "Radiology Technician", "OT Assistant"],
    exams: ["State Board Entrance"],
    higherStudies: ["B.Sc Paramedical", "Specialization Certs"],
    skillsLearned: ["Lab Testing", "Radiography", "Patient Support", "Clinical Observation"],
    studyMaterials: [{ title: "Lab Technician Handbook", type: "Guide", link: "https://www.who.int/", language: "English" }],
  },
];

const sampleDeadlines = [
  {
    title: "CUET UG Application Window",
    category: "Entrance Test",
    date: new Date("2026-07-10"),
    state: "National",
    relatedCourse: "Multiple UG Courses",
    reminderRule: "7 days before",
    source: { label: "Public application calendar", url: "https://example.com/cuet", lastVerifiedAt: new Date("2026-05-20") },
  },
  {
    title: "MHT-CET Counseling Registration",
    category: "Counseling",
    date: new Date("2026-07-22"),
    state: "Maharashtra",
    relatedCourse: "Engineering and Pharmacy",
    reminderRule: "3 days before",
    source: { label: "State counseling notice", url: "https://example.com/cet", lastVerifiedAt: new Date("2026-05-21") },
  },
  {
    title: "National Merit Scholarship Upload Deadline",
    category: "Scholarship",
    date: new Date("2026-08-05"),
    state: "National",
    relatedCourse: "Any UG Program",
    reminderRule: "5 days before",
    source: { label: "Scholarship bulletin", url: "https://example.com/scholarship", lastVerifiedAt: new Date("2026-05-19") },
  },
];

const roadmapNodes = [
  { nodeId: "after-10th", label: "After 10th", category: "stage", depth: 0, stage: "After 10th", summary: "The starting point for major higher-secondary and vocational pathways.", visibleIn: ["public", "personalized"], position: { x: 40, y: 260 } },
  { nodeId: "science-stream", label: "Science", category: "stream", depth: 1, stage: "Higher Secondary", summary: "For students interested in math, biology, research, and technical pathways.", visibleIn: ["public", "personalized"], position: { x: 280, y: 70 } },
  { nodeId: "commerce-stream", label: "Commerce", category: "stream", depth: 1, stage: "Higher Secondary", summary: "For business, accounting, economics, and management-oriented routes.", visibleIn: ["public", "personalized"], position: { x: 280, y: 250 } },
  { nodeId: "arts-stream", label: "Arts", category: "stream", depth: 1, stage: "Higher Secondary", summary: "For humanities, communication, social sciences, law, and public service.", visibleIn: ["public", "personalized"], position: { x: 280, y: 430 } },
  { nodeId: "polytechnic", label: "Polytechnic Diploma", category: "stage", depth: 1, stage: "Vocational", summary: "A practical diploma path after 10th for engineering and technical roles.", visibleIn: ["public"], position: { x: 280, y: 610 } },
  { nodeId: "iti", label: "ITI", category: "stage", depth: 1, stage: "Vocational", summary: "Hands-on technical training through trade-focused certificates.", visibleIn: ["public"], position: { x: 280, y: 790 } },
  { nodeId: "12th-science-pcm", label: "12th Science PCM", category: "stage", depth: 2, stage: "Class 12", summary: "Physics, Chemistry, Mathematics pathway for engineering and computing.", requiredStream: "Science", visibleIn: ["public", "personalized"], position: { x: 560, y: 20 } },
  { nodeId: "science-pcm", label: "PCM", category: "stream", depth: 2, stage: "Science Specialization", summary: "Mathematics-focused science combination for engineering, NDA, and technical degrees.", requiredStream: "Science", visibleIn: ["public", "personalized"], position: { x: 560, y: 120 } },
  { nodeId: "science-pcb", label: "PCB", category: "stream", depth: 2, stage: "Science Specialization", summary: "Biology-focused science combination for medicine, nursing, and allied health.", requiredStream: "Science", visibleIn: ["public"], position: { x: 560, y: 220 } },
  { nodeId: "12th-commerce", label: "12th Commerce", category: "stage", depth: 2, stage: "Class 12", summary: "Commerce route for business, accounting, finance, and management studies.", requiredStream: "Commerce", visibleIn: ["public", "personalized"], position: { x: 560, y: 340 } },
  { nodeId: "12th-arts", label: "12th Arts", category: "stage", depth: 2, stage: "Class 12", summary: "Humanities route for law, media, psychology, and public service tracks.", requiredStream: "Arts", visibleIn: ["public", "personalized"], position: { x: 560, y: 500 } },
  { nodeId: "open-school", label: "Open School", category: "stage", depth: 2, stage: "Alternative Route", summary: "Flexible schooling route that keeps later degree and vocational options open.", visibleIn: ["public"], position: { x: 560, y: 690 } },
  { nodeId: "btech-cse", label: "B.Tech CSE", category: "course", depth: 3, stage: "Undergraduate", duration: "4 years", fees: "INR 50k - 15L", requiredStream: "PCM", entranceExams: ["JEE Main", "JEE Advanced", "MHT-CET"], skills: ["Programming", "Problem Solving"], careerOptions: ["Software Engineer", "AI Engineer"], summary: "A flagship engineering route into software, AI, and advanced computing careers.", visibleIn: ["public", "personalized"], position: { x: 900, y: 10 } },
  { nodeId: "bca", label: "BCA", category: "course", depth: 3, stage: "Undergraduate", duration: "3 years", fees: "INR 40k - 3L", requiredStream: "Any stream", entranceExams: ["CUET UG", "University Entrance"], skills: ["Programming", "Web Development"], careerOptions: ["Software Developer", "QA Engineer"], summary: "A flexible computing degree that suits students from multiple streams.", visibleIn: ["public", "personalized"], position: { x: 900, y: 110 } },
  { nodeId: "bsc", label: "B.Sc", category: "course", depth: 3, stage: "Undergraduate", duration: "3 years", fees: "INR 20k - 2L", requiredStream: "Science", entranceExams: ["CUET UG"], skills: ["Research", "Analytical Thinking"], careerOptions: ["Research Scientist", "Professor"], summary: "A broad science pathway that supports research and academic careers.", visibleIn: ["public"], position: { x: 900, y: 210 } },
  { nodeId: "nda", label: "NDA", category: "exam", depth: 3, stage: "Defence Entry", duration: "3 years training", fees: "Sponsored", requiredStream: "PCM preferred for Air Force / Navy", entranceExams: ["NDA Exam"], skills: ["Discipline", "Leadership"], careerOptions: ["Armed Forces"], summary: "A national defence route for Army, Navy, and Air Force entry.", visibleIn: ["public"], position: { x: 900, y: 310 } },
  { nodeId: "mbbs", label: "MBBS", category: "course", depth: 3, stage: "Undergraduate", duration: "5.5 years", fees: "INR 50k - 25L", requiredStream: "PCB", entranceExams: ["NEET UG"], skills: ["Clinical Observation", "Patient Care"], careerOptions: ["Doctor"], summary: "The core medical degree for becoming a physician or specialist.", visibleIn: ["public"], position: { x: 900, y: 410 } },
  { nodeId: "bsc-nursing", label: "B.Sc Nursing", category: "course", depth: 3, stage: "Undergraduate", duration: "4 years", fees: "INR 40k - 5L", requiredStream: "PCB", entranceExams: ["NEET UG", "Institute Entrance"], skills: ["Patient Care", "Observation"], careerOptions: ["Nurse"], summary: "A healthcare route for hospital, clinic, and public-health roles.", visibleIn: ["public"], position: { x: 900, y: 510 } },
  { nodeId: "bcom", label: "B.Com", category: "course", depth: 3, stage: "Undergraduate", duration: "3 years", fees: "INR 20k - 2L", requiredStream: "Commerce", entranceExams: ["CUET UG"], skills: ["Accounting", "Analysis"], careerOptions: ["Accountant", "Financial Analyst"], summary: "The classic undergraduate commerce degree for accounting and finance tracks.", visibleIn: ["public"], position: { x: 900, y: 610 } },
  { nodeId: "bba", label: "BBA", category: "course", depth: 3, stage: "Undergraduate", duration: "3 years", fees: "INR 60k - 6L", requiredStream: "Any stream", entranceExams: ["CUET UG", "IPMAT"], skills: ["Leadership", "Presentation"], careerOptions: ["Business Analyst", "Management Trainee"], summary: "A management-oriented undergraduate route for business careers.", visibleIn: ["public", "personalized"], position: { x: 900, y: 710 } },
  { nodeId: "chartered-accountancy", label: "CA", category: "course", depth: 3, stage: "Professional", duration: "4.5 years", fees: "Moderate", requiredStream: "Commerce preferred", entranceExams: ["CA Foundation"], skills: ["Accounting", "Taxation"], careerOptions: ["Chartered Accountant"], summary: "A high-value professional route in accounting, audit, and finance.", visibleIn: ["public", "personalized"], position: { x: 900, y: 810 } },
  { nodeId: "company-secretary", label: "CS", category: "course", depth: 3, stage: "Professional", duration: "3-4 years", fees: "Moderate", requiredStream: "Commerce / Arts", entranceExams: ["CSEET"], skills: ["Compliance", "Corporate Law"], careerOptions: ["Company Secretary"], summary: "A corporate governance and compliance specialization pathway.", visibleIn: ["public"], position: { x: 900, y: 910 } },
  { nodeId: "cost-accountancy", label: "CMA", category: "course", depth: 3, stage: "Professional", duration: "3-4 years", fees: "Moderate", requiredStream: "Commerce", entranceExams: ["CMA Foundation"], skills: ["Costing", "Accounting"], careerOptions: ["Cost Accountant"], summary: "A commerce specialization focused on costing, management accounting, and controls.", visibleIn: ["public"], position: { x: 900, y: 1010 } },
  { nodeId: "ba", label: "BA", category: "course", depth: 3, stage: "Undergraduate", duration: "3 years", fees: "INR 20k - 2L", requiredStream: "Arts", entranceExams: ["CUET UG"], skills: ["Critical Thinking", "Writing"], careerOptions: ["Teacher", "Policy Analyst"], summary: "A broad humanities degree supporting education, policy, and social science careers.", visibleIn: ["public"], position: { x: 900, y: 1110 } },
  { nodeId: "journalism", label: "Journalism", category: "course", depth: 3, stage: "Undergraduate", duration: "3 years", fees: "INR 50k - 5L", requiredStream: "Arts / Commerce", entranceExams: ["CUET UG"], skills: ["Storytelling", "Interviewing"], careerOptions: ["Journalist", "Editor"], summary: "A media and communication path for reporting, content, and broadcasting careers.", visibleIn: ["public", "personalized"], position: { x: 900, y: 1210 } },
  { nodeId: "llb", label: "Law", category: "course", depth: 3, stage: "Undergraduate / Professional", duration: "5 years integrated / 3 years", fees: "INR 50k - 10L", requiredStream: "Any stream", entranceExams: ["CLAT"], skills: ["Reasoning", "Argumentation"], careerOptions: ["Lawyer", "Legal Analyst"], summary: "A legal studies pathway for advocacy, corporate law, and judiciary tracks.", visibleIn: ["public", "personalized"], position: { x: 900, y: 1310 } },
  { nodeId: "civil-services", label: "UPSC / Civil Services", category: "career", depth: 4, stage: "Career Goal", duration: "Long-term", fees: "Varies", requiredStream: "Any stream", entranceExams: ["UPSC CSE"], skills: ["General Awareness", "Writing", "Decision Making"], careerOptions: ["IAS", "IPS", "IFS"], summary: "A public-service pathway built on broad academic preparation and exam strategy.", visibleIn: ["public", "personalized"], position: { x: 1260, y: 1330 } },
  { nodeId: "diploma-design", label: "Design / Animation", category: "course", depth: 3, stage: "Diploma", duration: "1-4 years", fees: "INR 40k - 6L", requiredStream: "Any stream", entranceExams: ["NID DAT", "NIFT"], skills: ["Visual Design", "Creativity"], careerOptions: ["UI UX Designer", "Graphic Designer"], summary: "Creative pathway for digital design, branding, and visual storytelling careers.", visibleIn: ["public"], position: { x: 900, y: 1410 } },
  { nodeId: "hotel-management", label: "Hotel Management", category: "course", depth: 3, stage: "Diploma / Degree", duration: "1.5-4 years", fees: "INR 60k - 4L", requiredStream: "Any stream", entranceExams: ["NCHMCT JEE"], skills: ["Service Operations", "Communication"], careerOptions: ["Hotel Manager"], summary: "Hospitality route for hotels, tourism, restaurants, and guest services.", visibleIn: ["public"], position: { x: 900, y: 1510 } },
  { nodeId: "agriculture", label: "Agriculture", category: "course", depth: 3, stage: "Undergraduate", duration: "4 years", fees: "INR 30k - 4L", requiredStream: "Science", entranceExams: ["CUET UG", "State CET"], skills: ["Field Research", "Biology"], careerOptions: ["Agricultural Scientist"], summary: "Agriculture and allied sciences pathway for farm systems and agri innovation.", visibleIn: ["public"], position: { x: 900, y: 1610 } },
  { nodeId: "veterinary", label: "Veterinary", category: "course", depth: 3, stage: "Undergraduate", duration: "5.5 years", fees: "INR 40k - 6L", requiredStream: "PCB", entranceExams: ["NEET UG", "State Veterinary Entrance"], skills: ["Animal Care", "Observation"], careerOptions: ["Veterinarian"], summary: "Animal health pathway for clinical, farm, and research careers.", visibleIn: ["public"], position: { x: 900, y: 1710 } },
  { nodeId: "software-engineer", label: "Software Engineer", category: "career", depth: 4, stage: "Career", summary: "Builds applications, services, and systems across software teams.", skills: ["Programming", "Problem Solving"], visibleIn: ["public", "personalized"], position: { x: 1260, y: 40 } },
  { nodeId: "data-scientist", label: "Data Scientist", category: "career", depth: 4, stage: "Career", summary: "Applies data analysis, ML, and experimentation to product and business problems.", skills: ["Statistics", "Python", "Machine Learning"], visibleIn: ["public"], position: { x: 1260, y: 130 } },
  { nodeId: "ai-engineer", label: "AI Engineer", category: "career", depth: 4, stage: "Career", summary: "Designs and ships AI-powered systems and intelligent applications.", skills: ["AI", "Programming", "Data"], visibleIn: ["public"], position: { x: 1260, y: 220 } },
  { nodeId: "research-scientist", label: "Research Scientist", category: "career", depth: 4, stage: "Career", summary: "Works on advanced scientific inquiry across labs, academia, or R&D.", skills: ["Research", "Analysis"], visibleIn: ["public"], position: { x: 1260, y: 310 } },
  { nodeId: "professor", label: "Professor", category: "career", depth: 4, stage: "Career", summary: "Academic teaching and research role in higher education.", skills: ["Teaching", "Research"], visibleIn: ["public"], position: { x: 1260, y: 400 } },
  { nodeId: "armed-forces", label: "Armed Forces", category: "career", depth: 4, stage: "Career", summary: "A defence services path built on discipline, leadership, and service.", skills: ["Leadership", "Discipline"], visibleIn: ["public"], position: { x: 1260, y: 490 } },
  { nodeId: "doctor", label: "Doctor", category: "career", depth: 4, stage: "Career", summary: "Medical diagnosis, treatment, and patient care across specializations.", skills: ["Clinical Care", "Decision Making"], visibleIn: ["public"], position: { x: 1260, y: 580 } },
  { nodeId: "nurse", label: "Nurse", category: "career", depth: 4, stage: "Career", summary: "Patient care and clinical coordination in healthcare settings.", skills: ["Observation", "Patient Care"], visibleIn: ["public"], position: { x: 1260, y: 670 } },
  { nodeId: "chartered-accountant", label: "Chartered Accountant", category: "career", depth: 4, stage: "Career", summary: "Professional finance role in audit, taxation, and corporate accounts.", skills: ["Accounting", "Audit"], visibleIn: ["public", "personalized"], position: { x: 1260, y: 760 } },
  { nodeId: "company-secretary-career", label: "Company Secretary", category: "career", depth: 4, stage: "Career", summary: "Corporate governance and compliance specialist role.", skills: ["Corporate Law", "Compliance"], visibleIn: ["public"], position: { x: 1260, y: 850 } },
  { nodeId: "cost-accountant", label: "Cost Accountant", category: "career", depth: 4, stage: "Career", summary: "Specialist finance role in costing, controls, and planning.", skills: ["Costing", "Analysis"], visibleIn: ["public"], position: { x: 1260, y: 940 } },
  { nodeId: "journalist", label: "Journalist", category: "career", depth: 4, stage: "Career", summary: "Reporting and storytelling role across digital, print, and broadcast media.", skills: ["Reporting", "Writing"], visibleIn: ["public", "personalized"], position: { x: 1260, y: 1030 } },
  { nodeId: "lawyer", label: "Lawyer", category: "career", depth: 4, stage: "Career", summary: "Legal practice role in litigation, advisory, or corporate law.", skills: ["Reasoning", "Advocacy"], visibleIn: ["public", "personalized"], position: { x: 1260, y: 1120 } },
  { nodeId: "uiux-designer", label: "UI UX Designer", category: "career", depth: 4, stage: "Career", summary: "Designs digital experiences, interfaces, and product journeys.", skills: ["Design Thinking", "Wireframing"], visibleIn: ["public"], position: { x: 1260, y: 1210 } },
  { nodeId: "hotel-manager", label: "Hotel Manager", category: "career", depth: 4, stage: "Career", summary: "Leads guest services, operations, and hospitality teams.", skills: ["Service Management", "Communication"], visibleIn: ["public"], position: { x: 1260, y: 1300 } },
  { nodeId: "agricultural-scientist", label: "Agricultural Scientist", category: "career", depth: 4, stage: "Career", summary: "Works in crop systems, agricultural research, and agri innovation.", skills: ["Biology", "Field Research"], visibleIn: ["public"], position: { x: 1260, y: 1390 } },
  { nodeId: "veterinarian", label: "Veterinarian", category: "career", depth: 4, stage: "Career", summary: "Animal care and clinical health specialist.", skills: ["Animal Care", "Clinical Observation"], visibleIn: ["public"], position: { x: 1260, y: 1480 } },
  { nodeId: "mca", label: "MCA", category: "milestone", depth: 4, stage: "Higher Studies", duration: "2 years", summary: "A postgraduate computing upgrade after BCA or related degrees.", visibleIn: ["personalized"], position: { x: 1260, y: 1570 } },
  { nodeId: "mba", label: "MBA", category: "milestone", depth: 4, stage: "Higher Studies", duration: "2 years", summary: "A business leadership upgrade after BBA or another undergraduate route.", visibleIn: ["personalized"], position: { x: 1260, y: 1660 } },
  { nodeId: "tech-internship", label: "Internship", category: "milestone", depth: 4, stage: "Milestone", summary: "Industry exposure through projects, internships, and work-integrated learning.", visibleIn: ["personalized"], position: { x: 1260, y: 1750 } },
  { nodeId: "senior-engineer", label: "Senior Engineer", category: "milestone", depth: 5, stage: "Growth Milestone", summary: "Progression step after hands-on engineering delivery experience.", visibleIn: ["personalized"], position: { x: 1560, y: 40 } },
  { nodeId: "tech-lead", label: "Tech Lead", category: "milestone", depth: 6, stage: "Growth Milestone", summary: "Leadership milestone for product architecture, delivery, and mentoring.", visibleIn: ["personalized"], position: { x: 1820, y: 40 } },
  { nodeId: "business-analyst", label: "Business Analyst", category: "career", depth: 5, stage: "Career", summary: "Bridges business goals and execution through analysis and planning.", visibleIn: ["personalized"], position: { x: 1560, y: 1660 } },
  { nodeId: "product-manager", label: "Product Manager", category: "milestone", depth: 6, stage: "Growth Milestone", summary: "Owns product strategy, prioritization, and execution across teams.", visibleIn: ["personalized"], position: { x: 1820, y: 1660 } },
  { nodeId: "finance-manager", label: "Finance Manager", category: "milestone", depth: 5, stage: "Growth Milestone", summary: "A leadership finance role after accounting and business experience.", visibleIn: ["personalized"], position: { x: 1560, y: 760 } },
  { nodeId: "editor", label: "Editor", category: "milestone", depth: 5, stage: "Growth Milestone", summary: "A senior media role focused on editorial quality and content direction.", visibleIn: ["personalized"], position: { x: 1560, y: 1030 } },
  { nodeId: "bds", label: "BDS", category: "course", depth: 3, stage: "Undergraduate", duration: "5 years", fees: "INR 1L - 6L / year", requiredStream: "PCB", entranceExams: ["NEET UG"], skills: ["Precision", "Dental Surgery"], careerOptions: ["Dentist"], summary: "Professional dental surgery path.", visibleIn: ["public", "personalized"], position: { x: 900, y: 1810 } },
  { nodeId: "bpharm", label: "B.Pharm", category: "course", depth: 3, stage: "Undergraduate", duration: "4 years", fees: "INR 60k - 2L / year", requiredStream: "Science", entranceExams: ["MHT-CET", "State CET"], skills: ["Drug Formulation", "Chemical Analysis"], careerOptions: ["Pharmacist"], summary: "Undergraduate pharmacy education path.", visibleIn: ["public", "personalized"], position: { x: 900, y: 1910 } },
  { nodeId: "barch", label: "B.Arch", category: "course", depth: 3, stage: "Undergraduate", duration: "5 years", fees: "INR 80k - 3L / year", requiredStream: "PCM", entranceExams: ["NATA", "JEE Main"], skills: ["CAD Drawing", "Spatial Design"], careerOptions: ["Architect"], summary: "Undergraduate architectural planning degree.", visibleIn: ["public", "personalized"], position: { x: 900, y: 2010 } },
  { nodeId: "paramedical-diploma", label: "Paramedical Diploma", category: "course", depth: 3, stage: "Diploma", duration: "2 years", fees: "INR 20k - 80k / year", requiredStream: "Science", entranceExams: ["State Entrance"], skills: ["Lab Testing", "Radiography"], careerOptions: ["Lab Technician"], summary: "Diploma in medical laboratory and support techs.", visibleIn: ["public"], position: { x: 900, y: 2110 } },
  { nodeId: "dentist", label: "Dentist", category: "career", depth: 4, stage: "Career", summary: "Clinical dentist or surgeon diagnosing oral issues.", skills: ["Precision", "Patient Care"], visibleIn: ["public"], position: { x: 1260, y: 1810 } },
  { nodeId: "pharmacist", label: "Pharmacist", category: "career", depth: 4, stage: "Career", summary: "Dispensing medicines, chemical testing, and quality control.", skills: ["Drug Knowledge", "Attention to Detail"], visibleIn: ["public"], position: { x: 1260, y: 1910 } },
  { nodeId: "architect", label: "Architect", category: "career", depth: 4, stage: "Career", summary: "Designs buildings, structures, and interior spaces.", skills: ["Design", "CAD Drawing"], visibleIn: ["public"], position: { x: 1260, y: 2010 } },
  { nodeId: "lab-technician", label: "Lab Technician", category: "career", depth: 4, stage: "Career", summary: "Conducts blood and chemical tests in diagnostic labs.", skills: ["Lab Operations", "Clinical Chemistry"], visibleIn: ["public"], position: { x: 1260, y: 2110 } },
  { nodeId: "civil-engineer", label: "Civil Engineer", category: "career", depth: 4, stage: "Career", summary: "Plans and designs roads, bridges, and infrastructure.", skills: ["Physics", "Construction Planning"], visibleIn: ["public"], position: { x: 1260, y: 2210 } },
  { nodeId: "pilot", label: "Pilot", category: "career", depth: 4, stage: "Career", summary: "Operates aircraft for commercial airlines or defence.", skills: ["Spatial Awareness", "Crisis Management"], visibleIn: ["public"], position: { x: 1260, y: 2310 } },
  { nodeId: "police-officer", label: "Police Officer", category: "career", depth: 4, stage: "Career", summary: "Enforces law, maintains public order, and investigates crimes.", skills: ["Crisis Management", "Law Enforcement"], visibleIn: ["public"], position: { x: 1260, y: 2410 } },
  { nodeId: "graphic-designer", label: "Graphic Designer", category: "career", depth: 4, stage: "Career", summary: "Creates visuals, brand assets, and digital art.", skills: ["Creativity", "Visual Software"], visibleIn: ["public"], position: { x: 1260, y: 2510 } },
  { nodeId: "teacher", label: "Teacher", category: "career", depth: 4, stage: "Career", summary: "Teaches primary or secondary school students.", skills: ["Communication", "Pedagogy"], visibleIn: ["public"], position: { x: 1260, y: 2610 } },
];

const roadmapEdges = [
  { edgeId: "after10-science", sourceId: "after-10th", targetId: "science-stream", label: "Choose stream", visibleIn: ["public"] },
  { edgeId: "after10-commerce", sourceId: "after-10th", targetId: "commerce-stream", label: "Choose stream", visibleIn: ["public"] },
  { edgeId: "after10-arts", sourceId: "after-10th", targetId: "arts-stream", label: "Choose stream", visibleIn: ["public"] },
  { edgeId: "after10-polytechnic", sourceId: "after-10th", targetId: "polytechnic", label: "Vocational option", visibleIn: ["public"] },
  { edgeId: "after10-iti", sourceId: "after-10th", targetId: "iti", label: "Vocational option", visibleIn: ["public"] },
  { edgeId: "science-pcm-edge", sourceId: "science-stream", targetId: "science-pcm", label: "Specialize", visibleIn: ["public"] },
  { edgeId: "science-pcb-edge", sourceId: "science-stream", targetId: "science-pcb", label: "Specialize", visibleIn: ["public"] },
  { edgeId: "science-12-edge", sourceId: "science-stream", targetId: "12th-science-pcm", label: "Continue to 12th", visibleIn: ["public"] },
  { edgeId: "commerce-12-edge", sourceId: "commerce-stream", targetId: "12th-commerce", label: "Continue to 12th", visibleIn: ["public"] },
  { edgeId: "arts-12-edge", sourceId: "arts-stream", targetId: "12th-arts", label: "Continue to 12th", visibleIn: ["public"] },
  { edgeId: "iti-open-school-edge", sourceId: "iti", targetId: "open-school", label: "Alternative progression", visibleIn: ["public"] },
  { edgeId: "polytechnic-open-school-edge", sourceId: "polytechnic", targetId: "open-school", label: "Alternative progression", visibleIn: ["public"] },
  { edgeId: "pcm-btech", sourceId: "science-pcm", targetId: "btech-cse", label: "Can take", visibleIn: ["public"] },
  { edgeId: "pcm-bca", sourceId: "science-pcm", targetId: "bca", label: "Can take", visibleIn: ["public"] },
  { edgeId: "pcm-bsc", sourceId: "science-pcm", targetId: "bsc", label: "Can take", visibleIn: ["public"] },
  { edgeId: "pcm-nda", sourceId: "science-pcm", targetId: "nda", label: "Can take", visibleIn: ["public"] },
  { edgeId: "pcb-mbbs", sourceId: "science-pcb", targetId: "mbbs", label: "Can take", visibleIn: ["public"] },
  { edgeId: "pcb-nursing", sourceId: "science-pcb", targetId: "bsc-nursing", label: "Can take", visibleIn: ["public"] },
  { edgeId: "pcb-agriculture", sourceId: "science-pcb", targetId: "agriculture", label: "Can take", visibleIn: ["public"] },
  { edgeId: "pcb-veterinary", sourceId: "science-pcb", targetId: "veterinary", label: "Can take", visibleIn: ["public"] },
  { edgeId: "commerce-bcom", sourceId: "12th-commerce", targetId: "bcom", label: "Can take", visibleIn: ["public"] },
  { edgeId: "commerce-bba", sourceId: "12th-commerce", targetId: "bba", label: "Can take", visibleIn: ["public"] },
  { edgeId: "commerce-ca", sourceId: "12th-commerce", targetId: "chartered-accountancy", label: "Professional route", visibleIn: ["public"] },
  { edgeId: "commerce-cs", sourceId: "12th-commerce", targetId: "company-secretary", label: "Professional route", visibleIn: ["public"] },
  { edgeId: "commerce-cma", sourceId: "12th-commerce", targetId: "cost-accountancy", label: "Professional route", visibleIn: ["public"] },
  { edgeId: "arts-ba", sourceId: "12th-arts", targetId: "ba", label: "Can take", visibleIn: ["public"] },
  { edgeId: "arts-journalism", sourceId: "12th-arts", targetId: "journalism", label: "Can take", visibleIn: ["public"] },
  { edgeId: "arts-law", sourceId: "12th-arts", targetId: "llb", label: "Can take", visibleIn: ["public"] },
  { edgeId: "arts-upsc", sourceId: "12th-arts", targetId: "civil-services", label: "Career goal", visibleIn: ["public"] },
  { edgeId: "open-design", sourceId: "open-school", targetId: "diploma-design", label: "Can take", visibleIn: ["public"] },
  { edgeId: "open-hotel", sourceId: "open-school", targetId: "hotel-management", label: "Can take", visibleIn: ["public"] },
  { edgeId: "btech-software", sourceId: "btech-cse", targetId: "software-engineer", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "btech-data", sourceId: "btech-cse", targetId: "data-scientist", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "btech-ai", sourceId: "btech-cse", targetId: "ai-engineer", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "bca-software", sourceId: "bca", targetId: "software-engineer", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "bsc-research", sourceId: "bsc", targetId: "research-scientist", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "bsc-professor", sourceId: "bsc", targetId: "professor", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "nda-armed", sourceId: "nda", targetId: "armed-forces", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "mbbs-doctor", sourceId: "mbbs", targetId: "doctor", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "nursing-nurse", sourceId: "bsc-nursing", targetId: "nurse", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "bcom-accounting", sourceId: "bcom", targetId: "chartered-accountant", label: "Supports", visibleIn: ["public"] },
  { edgeId: "bba-business", sourceId: "bba", targetId: "business-analyst", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "ca-career", sourceId: "chartered-accountancy", targetId: "chartered-accountant", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "cs-career", sourceId: "company-secretary", targetId: "company-secretary-career", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "cma-career", sourceId: "cost-accountancy", targetId: "cost-accountant", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "journalism-career", sourceId: "journalism", targetId: "journalist", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "law-career", sourceId: "llb", targetId: "lawyer", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "design-career", sourceId: "diploma-design", targetId: "uiux-designer", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "hotel-career", sourceId: "hotel-management", targetId: "hotel-manager", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "agri-career", sourceId: "agriculture", targetId: "agricultural-scientist", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "vet-career", sourceId: "veterinary", targetId: "veterinarian", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "pcb-bds", sourceId: "science-pcb", targetId: "bds", label: "Can take", visibleIn: ["public"] },
  { edgeId: "bds-dentist", sourceId: "bds", targetId: "dentist", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "pcb-bpharm", sourceId: "science-pcb", targetId: "bpharm", label: "Can take", visibleIn: ["public"] },
  { edgeId: "bpharm-pharmacist", sourceId: "bpharm", targetId: "pharmacist", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "pcb-paramedical", sourceId: "science-pcb", targetId: "paramedical-diploma", label: "Can take", visibleIn: ["public"] },
  { edgeId: "paramedical-labtech", sourceId: "paramedical-diploma", targetId: "lab-technician", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "pcm-barch", sourceId: "science-pcm", targetId: "barch", label: "Can take", visibleIn: ["public"] },
  { edgeId: "barch-architect", sourceId: "barch", targetId: "architect", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "polytechnic-civil", sourceId: "polytechnic", targetId: "civil-engineer", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "nda-pilot", sourceId: "nda", targetId: "pilot", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "arts-police", sourceId: "arts-stream", targetId: "police-officer", label: "UPSC/State entry", visibleIn: ["public"] },
  { edgeId: "ba-teacher", sourceId: "ba", targetId: "teacher", label: "Leads to", visibleIn: ["public"] },
  { edgeId: "design-graphic", sourceId: "diploma-design", targetId: "graphic-designer", label: "Leads to", visibleIn: ["public"] },
];

async function upsertMany(model, docs, key) {
  await Promise.all(
    docs.map((doc) =>
      model.findOneAndReplace({ [key]: doc[key] }, doc, {
        upsert: true,
        returnDocument: "after",
        runValidators: true,
        setDefaultsOnInsert: true,
      })
    )
  );
}

async function seedDatabase() {
  await College.deleteMany({ slug: { $in: obsoleteCollegeSlugs } });

  await upsertMany(Question, sampleQuestions, "order");
  await upsertMany(Course, sampleCourses, "slug");
  await Deadline.deleteMany({ title: { $in: sampleDeadlines.map((deadline) => deadline.title) } });
  await upsertMany(RoadmapNode, roadmapNodes, "nodeId");
  await upsertMany(RoadmapEdge, roadmapEdges, "edgeId");

  const courses = await Course.find();
  const courseMap = Object.fromEntries(courses.map((course) => [course.slug, course._id]));

  const resources = [
    {
      title: "Programming Foundations Roadmap",
      subject: "Computer Science",
      format: "Roadmap",
      link: "https://roadmap.sh/",
      language: "English",
      courseMapping: [courseMap["btech-cse"], courseMap["bca"], courseMap["bsc-computer-science"]].filter(Boolean),
      description: "Beginner-friendly roadmap for software, AI, and core computing concepts.",
    },
    {
      title: "Commerce Career Kickstart",
      subject: "Commerce",
      format: "Guide",
      link: "https://example.com/commerce-pack",
      language: "English",
      courseMapping: [courseMap["bcom"], courseMap["bba"], courseMap["chartered-accountancy"]].filter(Boolean),
      description: "A starter pack for business, finance, and accounting pathways.",
    },
    {
      title: "Creative Path Explorer",
      subject: "Design and Media",
      format: "Toolkit",
      link: "https://example.com/design-kit",
      language: "English",
      courseMapping: [courseMap["diploma-graphic-design"], courseMap["ba-journalism-mass-communication"]].filter(Boolean),
      description: "Starter references for media, visual thinking, and digital design.",
    },
  ];

  await upsertMany(Resource, resources, "title");

  const colleges = [
    {
      name: "COEP Technological University",
      slug: "coep-technological-university",
      location: { state: "Maharashtra", city: "Pune", address: "Shivajinagar, Pune", lat: 18.5294, lng: 73.8567 },
      type: "Government",
      mediumOfInstruction: ["English"],
      coursesOffered: [courseMap["btech-cse"], courseMap["bsc-computer-science"]].filter(Boolean),
      facilities: ["Labs", "Library", "Innovation Cell", "Wi-Fi"],
      hostel: true,
      library: true,
      lab: true,
      internet: true,
      feesRange: "INR 75,000 - 1,60,000 / year",
      cutoffInfo: "Engineering admission typically follows state and national entrance ranks.",
      contact: { website: "https://www.coep.org.in/", phone: "+91 20 25507000", email: "admissions@coep.ac.in" },
      source: { label: "Official institute site", url: "https://www.coep.org.in/", lastVerifiedAt: new Date("2026-06-01") },
      verifiedStatus: "verified",
    },
    {
      name: "Christ University",
      slug: "christ-university",
      location: { state: "Karnataka", city: "Bengaluru", address: "Hosur Road, Bengaluru", lat: 12.9352, lng: 77.6057 },
      type: "Private",
      mediumOfInstruction: ["English"],
      coursesOffered: [courseMap["bca"], courseMap["bba"], courseMap["ba-psychology"]].filter(Boolean),
      facilities: ["Library", "Seminar Halls", "Career Center", "Wi-Fi"],
      hostel: true,
      library: true,
      lab: true,
      internet: true,
      feesRange: "INR 80,000 - 2,50,000 / year",
      cutoffInfo: "Program-specific application, entrance, and interview process.",
      contact: { website: "https://christuniversity.in/", phone: "+91 80 40129000", email: "admissions@christuniversity.in" },
      source: { label: "Official university site", url: "https://christuniversity.in/", lastVerifiedAt: new Date("2026-06-01") },
      verifiedStatus: "verified",
    },
    {
      name: "Shri Ram College of Commerce",
      slug: "shri-ram-college-of-commerce",
      location: { state: "Delhi", city: "New Delhi", address: "North Campus, Delhi University", lat: 28.6886, lng: 77.2087 },
      type: "Government-aided",
      mediumOfInstruction: ["English", "Hindi"],
      coursesOffered: [courseMap["bcom"], courseMap["bba"]].filter(Boolean),
      facilities: ["Library", "Commerce Labs", "Career Cell"],
      hostel: false,
      library: true,
      lab: true,
      internet: true,
      feesRange: "INR 35,000 - 90,000 / year",
      cutoffInfo: "UG admission usually follows central counselling and merit trends.",
      contact: { website: "https://srcc.edu/", phone: "+91 11 27666519", email: "principal@srcc.du.ac.in" },
      source: { label: "Official college site", url: "https://srcc.edu/", lastVerifiedAt: new Date("2026-06-01") },
      verifiedStatus: "verified",
    },
    {
      name: "Lady Shri Ram College for Women",
      slug: "lady-shri-ram-college",
      location: { state: "Delhi", city: "New Delhi", address: "Lajpat Nagar, New Delhi", lat: 28.5665, lng: 77.2431 },
      type: "Government-aided",
      mediumOfInstruction: ["English", "Hindi"],
      coursesOffered: [courseMap["ba-psychology"], courseMap["ba-journalism-mass-communication"], courseMap["llb"]].filter(Boolean),
      facilities: ["Media Lab", "Library", "Student Counseling", "Wi-Fi"],
      hostel: false,
      library: true,
      lab: true,
      internet: true,
      feesRange: "INR 30,000 - 1,10,000 / year",
      cutoffInfo: "Program admission depends on central counselling and college-specific criteria.",
      contact: { website: "https://lsr.edu.in/", phone: "+91 11 45494949", email: "info@lsr.edu.in" },
      source: { label: "Official college site", url: "https://lsr.edu.in/", lastVerifiedAt: new Date("2026-06-01") },
      verifiedStatus: "verified",
    },
    {
      name: "Institute of Hotel Management Pusa",
      slug: "ihm-pusa",
      location: { state: "Delhi", city: "New Delhi", address: "Pusa, New Delhi", lat: 28.6364, lng: 77.1587 },
      type: "Government",
      mediumOfInstruction: ["English"],
      coursesOffered: [courseMap["diploma-hotel-management"]].filter(Boolean),
      facilities: ["Training Kitchens", "Library", "Placement Cell"],
      hostel: true,
      library: true,
      lab: true,
      internet: true,
      feesRange: "INR 60,000 - 1,80,000 / year",
      cutoffInfo: "Hospitality admission generally follows NCHMCT JEE and institute rules.",
      contact: { website: "https://www.ihmpusa.net/", phone: "+91 11 25841411", email: "principal@ihmpusa.net" },
      source: { label: "Official institute site", url: "https://www.ihmpusa.net/", lastVerifiedAt: new Date("2026-06-01") },
      verifiedStatus: "verified",
    },
    {
      name: "National Institute of Fashion Technology Bengaluru",
      slug: "nift-bengaluru",
      location: { state: "Karnataka", city: "Bengaluru", address: "H.S.R Layout, Bengaluru", lat: 12.9116, lng: 77.6477 },
      type: "Government",
      mediumOfInstruction: ["English"],
      coursesOffered: [courseMap["diploma-graphic-design"]].filter(Boolean),
      facilities: ["Design Studios", "Library", "Industry Projects"],
      hostel: false,
      library: true,
      lab: true,
      internet: true,
      feesRange: "INR 1,20,000 - 3,00,000 / year",
      cutoffInfo: "Design admission depends on NIFT entrance and portfolio evaluation.",
      contact: { website: "https://www.nift.ac.in/bengaluru/", phone: "+91 80 22552550", email: "nift.bengaluru@nift.ac.in" },
      source: { label: "Official institute site", url: "https://www.nift.ac.in/bengaluru/", lastVerifiedAt: new Date("2026-06-01") },
      verifiedStatus: "verified",
    },
    {
      name: "DKTE Society's Textile Engineering Institute",
      slug: "dkte-society-textile-engineering-institute",
      location: { state: "Maharashtra", city: "Kolhapur", address: "Rajwada Post Box No 130, Ichalkaranji", lat: 16.6961, lng: 74.4641 },
      type: "Private",
      mediumOfInstruction: ["English"],
      coursesOffered: [courseMap["btech-cse"], courseMap["bpharm"]].filter(Boolean),
      facilities: ["Labs", "Library", "Textile Design Labs", "Wi-Fi"],
      hostel: true,
      library: true,
      lab: true,
      internet: true,
      feesRange: "INR 85,000 - 1,40,000 / year",
      cutoffInfo: "Admissions follow MHT-CET and JEE Main entrance results.",
      contact: { website: "http://www.dktes.com/", phone: "+91 230 2439515", email: "info@dktes.com" },
      source: { label: "Official institute site", url: "http://www.dktes.com/", lastVerifiedAt: new Date("2026-06-01") },
      verifiedStatus: "verified",
    },
  ];

  await upsertMany(College, colleges, "slug");
}

async function runSeed() {
  await connectDatabase();
  await seedDatabase();
  console.log("Seed completed.");
  process.exit(0);
}

if (require.main === module) {
  runSeed().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

module.exports = { seedDatabase };
