import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Button from "../components/ui/Button";
import SectionCard from "../components/ui/SectionCard";
import { fetchAssessmentRoadmap } from "../services/platformService";

export default function PersonalizedRoadmapPage() {
  const [roadmap, setRoadmap] = useState(null); const [selected, setSelected] = useState(null); const [error, setError] = useState("");
  useEffect(() => { fetchAssessmentRoadmap().then(setRoadmap).catch(err => setError(err.response?.data?.message || "Unable to create your roadmap.")); }, []);
  if (error) return <SectionCard>{error}</SectionCard>; if (!roadmap) return <SectionCard><p className="section-title">Creating your personalized roadmap...</p><p className="mt-2 text-sm text-slate-600">Using your saved assessment and verified pathway data.</p></SectionCard>;
  return <div className="space-y-6"><SectionCard className="bg-[linear-gradient(135deg,#0f172a,#1e3a8a)] text-white"><p className="text-sm font-semibold uppercase tracking-wider text-blue-200">{roadmap.title}</p><h1 className="mt-2 text-3xl font-black">{roadmap.currentStage.title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-blue-100">{roadmap.intro}</p></SectionCard><div className="grid gap-6 lg:grid-cols-2">{roadmap.pathways.map(pathway => <SectionCard key={pathway.pathwayName}><p className="text-xs font-semibold uppercase tracking-wider text-blue-800">Pathway {pathway.rank}</p><div className="mt-2 flex justify-between gap-3"><h2 className="text-2xl font-bold">{pathway.pathwayName}</h2><span className="font-bold text-blue-800">{pathway.matchScore}/100</span></div><p className="mt-1 text-sm font-semibold text-emerald-700">{pathway.matchLevel}</p><p className="mt-4 text-sm leading-6 text-slate-600">{pathway.whyItMatches}</p><div className="mt-6 space-y-3 border-l-2 border-blue-200 pl-5">{pathway.nodes.map((node, index) => <button key={node.id} type="button" onClick={() => setSelected(node)} className="block w-full rounded-2xl border border-slate-200 bg-white p-4 text-left transition hover:border-blue-400 hover:bg-blue-50"><p className="text-xs font-semibold uppercase tracking-wider text-blue-700">{index === 0 ? "Next step" : node.type.replaceAll("_", " ")}</p><p className="mt-1 font-bold text-slate-900">{node.title}</p><p className="mt-1 text-sm text-slate-600">{node.description}</p></button>)}</div><p className="mt-5 text-sm font-semibold text-slate-900">What to explore next</p><ol className="mt-2 list-decimal space-y-1 pl-5 text-sm text-slate-600">{pathway.nextSteps.map(step => <li key={step}>{step}</li>)}</ol></SectionCard>)}</div>{roadmap.explorationNote?.length ? <SectionCard><p className="section-title">Areas to explore</p><p className="mt-2 text-sm text-slate-600">You showed interest but some uncertainty in: {roadmap.explorationNote.join(", ")}. Learn more about the subjects, courses and types of work involved before deciding.</p></SectionCard> : null}{selected ? <SectionCard><div className="flex items-start justify-between gap-4"><div><p className="section-title">{selected.title}</p><p className="mt-2 text-sm text-slate-600">{selected.description}</p>{selected.duration ? <p className="mt-2 text-sm text-slate-600">Duration: {selected.duration}</p> : null}</div><Button variant="secondary" onClick={() => setSelected(null)}>Close</Button></div></SectionCard> : null}<SectionCard><p className="text-sm text-slate-600">{roadmap.disclaimer}</p><Link to="/results" className="mt-4 inline-flex"><Button variant="secondary">Return to assessment report</Button></Link></SectionCard></div>;
}
