import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Button from "../components/ui/Button";
import SectionCard from "../components/ui/SectionCard";
import { fetchLatestAssessment } from "../services/platformService";
const names = { DEFENCE_SECURITY: "Defence & Security", AGRICULTURE_ALLIED: "Agriculture & Allied", SOCIAL_SCIENCE_HUMANITIES: "Social Science & Humanities", ARTS_MEDIA_CREATIVE: "Arts, Media & Creative", MEDICAL_HEALTH: "Medical & Health", COMMERCE_FINANCE_BUSINESS: "Commerce, Finance & Business", SCIENCE_ENGINEERING_TECH: "Science, Engineering & Technology" };
export default function ResultsPage() {
  const [report, setReport] = useState(null); useEffect(() => { fetchLatestAssessment().then(setReport).catch(() => null); }, []);
  if (!report?.result) return <SectionCard><p className="section-title">No results yet</p><Link to="/assessment" className="mt-4 inline-flex"><Button>Take the assessment</Button></Link></SectionCard>;
  const structured = report.structuredRecommendations; const explanation = report.aiExplanation;
  return <div className="space-y-6"><SectionCard><p className="text-sm font-semibold uppercase tracking-wider text-blue-800">After-10th report</p><h1 className="mt-2 text-3xl font-black">Your Interest Profile</h1><p className="mt-3 text-sm text-slate-600">Interest Fit (50%), Academic Fit (30%), and Preference Fit (20%) are calculated by the backend. {structured?.student?.marksDeclared ? "Marks are included." : "Marks are unavailable, so Interest and Preference are normalized to 100."}</p></SectionCard><SectionCard><div className="space-y-4">{report.result.results.map(item => <div key={item.categoryId}><div className="flex justify-between text-sm font-semibold"><span>{names[item.categoryId] || item.categoryId}</span><span>Interest Score: {item.interestIndex.toFixed(1)}/100</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-800" style={{ width: `${item.interestIndex}%` }} /></div><p className="mt-1 text-xs text-slate-500">Rank {item.rank} · Uncertainty: {item.uncertaintyRate}%</p></div>)}</div></SectionCard><div className="grid gap-6 lg:grid-cols-2"><SectionCard><p className="section-title">Calculated pathway matches</p><div className="mt-4 space-y-3">{structured?.recommendations.map(item => <div key={item.pathway} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><p className="font-bold">{item.pathway}</p><p className="font-semibold text-blue-800">{item.matchScore}/100</p></div><p className="mt-1 text-xs text-slate-600">Interest {item.interestFit} · Preference {item.preferenceFit} · Academic {item.academicFit === "UNAVAILABLE" ? "Unavailable" : item.academicFit}</p><p className="mt-1 text-xs text-slate-500">Eligibility: {item.eligibility.replaceAll("_", " ")}</p></div>)}</div></SectionCard><SectionCard><p className="section-title">Your personalized explanation</p>{explanation ? <div className="mt-4 space-y-4"><p className="text-sm leading-7 text-slate-700">{explanation.summary}</p>{explanation.recommendations.map(item => <div key={item.pathway} className="rounded-2xl bg-slate-50 p-4"><p className="font-bold">{item.pathway}</p><p className="mt-1 text-sm text-slate-600">{item.why}</p><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm text-slate-700">{item.nextSteps.map(step => <li key={step}>{step}</li>)}</ol></div>)}</div> : <p className="mt-4 text-sm text-slate-600">{report.aiExplanationError || "Add GEMINI_API_KEY to the backend environment to generate a student-friendly explanation and roadmap."}</p>}</SectionCard></div></div>;
}
