# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14sAh2JkKTjyv0wek89vYgCGSxjttOcEm

# AI-based Career Recommendation System

## 1. Setup

This section handles the installation of required libraries and imports. It also includes a cell to upload the student's PDF report card.
"""

# Install necessary libraries
!pip install PyPDF2 pandas numpy scikit-learn matplotlib seaborn
!pip install pdfplumber

# Import required libraries
import PyPDF2 # For PDF parsing
import pdfplumber # Another PDF parsing library, often more robust
import pandas as pd
import numpy as np
import re # For regular expressions
from google.colab import files # For file upload
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
import seaborn as sns

"""### Upload Report Card PDF

Please upload the student's PDF report card using the widget below. This will be used by the PDF parsing module.
"""

# Colab file upload cell
uploaded = files.upload()

# Get the name of the uploaded file
if uploaded:
    pdf_filename = list(uploaded.keys())[0]
    print(f'Uploaded file: {pdf_filename}')
else:
    pdf_filename = None
    print('No file uploaded. Please upload a PDF report card to proceed.')

"""## 2. PDF Parsing Module

This module extracts raw text from the uploaded PDF and uses regular expressions to pull out the student's name, subject names, and corresponding scores/grades. It aims to handle various formatting inconsistencies and present the data as a clean pandas DataFrame.
"""

def extract_text_from_pdf(pdf_path):
    """Extracts text from a PDF file using pdfplumber."""
    text = ''
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                text += page.extract_text() + '\n'
    except Exception as e:
        print(f"Error reading PDF with pdfplumber: {e}")
        # Fallback to PyPDF2 if pdfplumber fails
        try:
            with open(pdf_path, 'rb') as file:
                reader = PyPDF2.PdfReader(file)
                for page_num in range(len(reader.pages)):
                    text += reader.pages[page_num].extract_text() + '\n'
        except Exception as e_pypdf2:
            print(f"Error reading PDF with PyPDF2: {e_pypdf2}")
            return None
    return text

def parse_report_card(text):
    """Parses the extracted text to find student name, subjects, and scores."""
    student_name = 'Unknown Student'
    # Regex to find student name (e.g., 'Student Name: [Name]', 'Name: [Name]', 'Student: [Name]')
    name_patterns = [
        r'(?:Student Name|Name|Student)[:\\s]*([A-Za-z]+\\s[A-Za-z]+(?:\\s[A-Za-z]+)?)\\b',
        r'Student\\s+([A-Za-z]+\\s[A-Za-z]+(?:\\s[A-Za-z]+)?)\\b',
        r'Name\\s*:\\s*([A-Za-z]+\\s[A-Za-z]+(?:\\s[A-Za-z]+)?)\\b'
    ]
    for pattern in name_patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            student_name = match.group(1).strip()
            break

    # Regex to find subjects and scores/grades
    # This pattern tries to be flexible: Subject Name (score/grade), Subject Name score, Subject Name grade
    # It looks for words (subject name), then numbers (score), or letters (grade).
    subject_score_patterns = [
        r'([A-Za-z\\s]+?)(?:\\s*\\(?[\\s]*([A-DF][+-]?|[0-9]{1,3}(?:\\.[0-9]{1,2})?)[\\s]*\\)?)',
        r'([A-Za-z\\s]+?)\\s*:\\s*([A-DF][+-]?|[0-9]{1,3}(?:\\.[0-9]{1,2})?)'
    ]

    data = {'Subject': [], 'Score': []}
    for line in text.split('\n'):
        line = line.strip()
        if not line:
            continue

        for pattern in subject_score_patterns:
            matches = re.findall(pattern, line)
            for match in matches:
                subject = match[0].strip()
                score = match[1].strip()

                # Simple filtering to avoid capturing non-subject lines
                if len(subject.split()) > 1 and len(score) > 0 and 'total' not in subject.lower() and 'grade' not in subject.lower():
                    # Attempt to convert score to numeric if possible, otherwise keep as string
                    try:
                        score = float(score)
                    except ValueError:
                        pass # Keep as string if it's a letter grade
                    data['Subject'].append(subject)
                    data['Score'].append(score)
                    break # Found a match, move to next line

    df = pd.DataFrame(data)

    # Only apply .str operations if 'Subject' column exists and is not empty
    if not df.empty and pd.api.types.is_string_dtype(df['Subject']):
        # Clean up subject names (remove extra spaces, potential leading/trailing non-alpha chars)
        df['Subject'] = df['Subject'].str.replace(r'[^a-zA-Z\\s]', '', regex=True).str.strip()

    # Remove duplicate subjects (e.g., if extracted multiple times from different formats)
    if not df.empty:
        df = df.drop_duplicates(subset=['Subject'], keep='first')

    return student_name, df


# --- Execution of PDF Parsing ---
pdf_filename_actual = pdf_filename # Store original filename for reference
if pdf_filename:
    print(f"Parsing report card from {pdf_filename}...")
    report_card_text = extract_text_from_pdf(pdf_filename)

    if report_card_text and report_card_text.strip() != '':
        student_name, parsed_df = parse_report_card(report_card_text)
        if parsed_df.empty:
            print("Warning: No subject scores were successfully parsed from the PDF. Generating synthetic data for demo.")
            # Fallback to synthetic parsed_df if real parsing failed to yield data
            student_name = "Synthetic Student"
            parsed_df = pd.DataFrame({
                'Subject': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English', 'Computer Science'],
                'Score': [90, 85, 78, 70, 88, 92]
            })
    else:
        print("Failed to extract meaningful text from the PDF. Generating synthetic data for demo.")
        student_name = "Synthetic Student"
        parsed_df = pd.DataFrame({
            'Subject': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English', 'Computer Science'],
            'Score': [90, 85, 78, 70, 88, 92]
        })

    print(f"\nStudent Name: {student_name}")
    print("\nParsed Report Card Data (or synthetic for demo):")
    display(parsed_df)

    if parsed_df.empty:
        print("Critical Warning: parsed_df is empty even after synthetic generation. There might be an issue.")
else:
    print("No PDF file uploaded. Generating synthetic data for demo.")
    student_name = "Synthetic Student"
    parsed_df = pd.DataFrame({
        'Subject': ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'English', 'Computer Science'],
        'Score': [90, 85, 78, 70, 88, 92]
    })
    print(f"\nStudent Name: {student_name}")
    print("\nParsed Report Card Data (synthetic for demo):")
    display(parsed_df)

"""## 3. Interest Input

This section defines a simple mechanism for capturing the student's interest areas with weighted preference scores (1-5 scale). These interests will be combined with subject scores for career recommendations.
"""

# Student interest areas and their weighted preference scores (1-5 scale)
# You can modify this dictionary to reflect the student's actual interests.
# Key: Interest Area, Value: Preference Score
student_interests = {
    'Science': 4,
    'Mathematics': 5,
    'Arts': 2,
    'Commerce': 3,
    'Technology': 4,
    'Sports': 1,
    'Design': 2,
    'Humanities': 3,
    'Engineering': 5,
    'Medical': 4,
    'Business': 3
}

print("Student Interests and Preference Scores:")
for interest, score in student_interests.items():
    print(f"- {interest}: {score}")

# Convert interests to a DataFrame for easier merging/feature engineering later
interests_df = pd.DataFrame(list(student_interests.items()), columns=['Interest', 'Preference_Score'])
print("\nInterests DataFrame:")
display(interests_df)

"""## 4. Synthetic Training Dataset

Since a real dataset for this specific purpose is not readily available, a synthetic dataset is generated. This dataset maps combinations of subject scores and interest profiles to predefined career labels. The generation logic uses reasonable domain heuristics to ensure the data is not entirely random and reflects potential real-world relationships between academic performance, interests, and career paths.
"""

def generate_synthetic_data(num_samples=1000):
    """Generates a synthetic dataset for career recommendation."""
    np.random.seed(42) # for reproducibility

    # Define possible subjects and their typical score ranges
    subjects = ['Physics', 'Chemistry', 'Biology', 'Mathematics', 'English', 'History', 'Geography', 'Computer Science', 'Art', 'Economics']
    career_paths = ['Engineer', 'Doctor', 'Data Scientist', 'Teacher', 'Artist', 'Economist', 'Lawyer', 'Entrepreneur', 'Journalist', 'Scientist', 'Designer'] # Added Designer
    # Extended interest_areas to match those used in career logic
    interest_areas = ['Science', 'Mathematics', 'Arts', 'Commerce', 'Technology', 'Humanities', 'Engineering', 'Medical', 'Business', 'Sports', 'Design']

    data = []
    for _ in range(num_samples):
        sample = {}

        # Generate random scores for subjects (0-100)
        for subj in subjects:
            sample[subj] = np.random.randint(40, 100) # Assuming a pass mark of 40

        # Generate random interest preferences (1-5)
        for interest in interest_areas:
            sample[f'Interest_{interest}'] = np.random.randint(1, 6)

        # Assign career labels based on scores and interests (simplified logic)
        # Prioritize certain combinations
        if sample.get('Interest_Engineering', 0) >= 4 and sample['Mathematics'] >= 85 and sample['Physics'] >= 80:
            sample['Career'] = 'Engineer'
        elif sample.get('Interest_Medical', 0) >= 4 and sample['Biology'] >= 85 and sample['Chemistry'] >= 80:
            sample['Career'] = 'Doctor'
        elif sample.get('Interest_Technology', 0) >= 4 and sample['Mathematics'] >= 80 and sample['Computer Science'] >= 85:
            sample['Career'] = 'Data Scientist'
        elif sample.get('Interest_Humanities', 0) >= 4 and sample['English'] >= 85 and sample['History'] >= 80:
            sample['Career'] = 'Teacher'
        elif sample.get('Interest_Arts', 0) >= 4 and sample['Art'] >= 80:
            sample['Career'] = 'Artist'
        elif sample.get('Interest_Commerce', 0) >= 4 and sample['Economics'] >= 80 and sample['Mathematics'] >= 75:
            sample['Career'] = 'Economist'
        elif sample['Mathematics'] >= 90 and sample['Physics'] >= 90 and sample['Chemistry'] >= 90:
            sample['Career'] = np.random.choice(['Engineer', 'Scientist'])
        elif sample['English'] >= 90 and sample['History'] >= 90:
            sample['Career'] = np.random.choice(['Journalist', 'Lawyer'])
        elif sample['Art'] >= 70 and sample['English'] >= 70:
            sample['Career'] = np.random.choice(['Artist', 'Designer'])
        elif sample.get('Interest_Business', 0) >= 4 and sample['Economics'] >= 70:
            sample['Career'] = 'Entrepreneur'
        else:
            # Default assignment for less clear cases, or randomly pick one
            sample['Career'] = np.random.choice(career_paths)

        data.append(sample)

    return pd.DataFrame(data)

# Generate the synthetic dataset
synthetic_df = generate_synthetic_data(num_samples=1000)

print(f"Generated synthetic dataset with {len(synthetic_df)} samples and {len(synthetic_df.columns)} features.")
print("First 5 rows of the synthetic dataset:")
display(synthetic_df.head())
print("Career distribution in the synthetic dataset:")
display(synthetic_df['Career'].value_counts())

"""## 5. Feature Engineering

This section involves normalizing subject scores, encoding interest categories, and combining all relevant features into a feature matrix suitable for machine learning model training.
"""

# Identify numerical and categorical features
subject_cols = [col for col in synthetic_df.columns if col not in ['Career'] and not col.startswith('Interest_')]
interest_cols = [col for col in synthetic_df.columns if col.startswith('Interest_')]

# Preprocessing for numerical features (StandardScaler for scores)
# Preprocessing for categorical features (OneHotEncoder for interests, though they are already numerical here,
# for consistency we could treat them as categories if they were nominal)

# For simplicity, we'll just scale all numerical features for now.
# If 'Interest_' columns were true categories (e.g., 'Science', 'Arts' as values), we'd use OneHotEncoder.
# Since they are scores, we can scale them along with subject scores.

# Define preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), subject_cols + interest_cols) # Scale all numerical features
    ])

X = synthetic_df.drop('Career', axis=1)
y = synthetic_df['Career']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Apply preprocessing to training and testing data
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# Get feature names after preprocessing (useful for feature importance)
# This is a bit tricky with ColumnTransformer. For simplicity, we'll keep original names mapped to scaled features.
# The order will be subject_cols + interest_cols
feature_names = subject_cols + interest_cols

print("Shape of processed training data:", X_train_processed.shape)
print("Shape of processed testing data:", X_test_processed.shape)
print("Example of processed data (first 5 rows of X_train_processed):")
print(X_train_processed[:5])

"""## 6. Model Building (from scratch)

This section builds and trains two classification models: a Decision Tree Classifier and a Random Forest Classifier. The code explicitly shows the training logic and avoids using black-box APIs.
"""

# --- Decision Tree Classifier ---
print("\n--- Training Decision Tree Classifier ---")
dtree_model = DecisionTreeClassifier(random_state=42)
dtree_model.fit(X_train_processed, y_train)

# --- Random Forest Classifier ---
print("\n--- Training Random Forest Classifier ---")
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1) # n_jobs=-1 uses all available cores
rf_model.fit(X_train_processed, y_train)

print("Models trained successfully!")

"""## 7. Evaluation

This section evaluates the performance of both trained models using accuracy, confusion matrix, classification report, and a visualization of feature importance for the Random Forest model.
"""

def evaluate_model(model, X_test, y_test, model_name):
    """Evaluates a given model and prints performance metrics."""
    y_pred = model.predict(X_test)

    print(f"\n--- {model_name} Evaluation ---")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

# Evaluate Decision Tree
evaluate_model(dtree_model, X_test_processed, y_test, "Decision Tree")

# Evaluate Random Forest
evaluate_model(rf_model, X_test_processed, y_test, "Random Forest")

# Feature Importance for Random Forest
if hasattr(rf_model, 'feature_importances_') and feature_names:
    importances = rf_model.feature_importances_
    forest_importances = pd.Series(importances, index=feature_names)

    fig, ax = plt.subplots(figsize=(12, 7))
    forest_importances.sort_values(ascending=False).plot.bar(ax=ax)
    ax.set_title("Feature importances from Random Forest")
    ax.set_ylabel("Mean decrease in impurity")
    fig.tight_layout()
    plt.show()

"""## 8. Inference Function

This function `recommend_career(pdf_scores, interests)` takes the parsed PDF scores and student interest input, processes them, and returns the top 3 recommended careers along with their confidence percentages. We will use the Random Forest model for inference as it generally performs better.
"""

def recommend_career(student_parsed_df, student_interests_dict, preprocessor, model, top_n=3):
    """
    Recommends careers based on parsed student scores and interests.

    Args:
        student_parsed_df (pd.DataFrame): DataFrame with 'Subject' and 'Score' columns.
        student_interests_dict (dict): Dictionary of interest areas and preference scores.
        preprocessor: The fitted ColumnTransformer used for feature engineering.
        model: The trained machine learning model (e.g., RandomForestClassifier).
        top_n (int): Number of top career recommendations to return.

    Returns:
        list: A list of tuples, each containing (career, confidence_percentage).
    """

    # 1. Prepare student scores for prediction
    # Ensure all subjects from the training data are present, fill missing with a default (e.g., mean or lowest pass score)
    # Get subject columns from the preprocessor's numerical features
    trained_subjects = [col for col in preprocessor.transformers_[0][1].feature_names_in_ if not col.startswith('Interest_')]
    trained_interests = [col for col in preprocessor.transformers_[0][1].feature_names_in_ if col.startswith('Interest_')]

    student_input_data = {}

    # Fill subject scores
    for subj in trained_subjects:
        score_row = student_parsed_df[student_parsed_df['Subject'].str.contains(subj, case=False, na=False)]
        if not score_row.empty:
            # Assuming score is numerical, if letter grade, convert to a numeric equivalent
            score_val = score_row['Score'].iloc[0]
            if isinstance(score_val, str): # Simple conversion for grades
                if score_val.upper().startswith('A'): score_val = 90
                elif score_val.upper().startswith('B'): score_val = 75
                elif score_val.upper().startswith('C'): score_val = 60
                elif score_val.upper().startswith('D'): score_val = 45
                else: score_val = 40 # Default lowest pass for unknown grades
            student_input_data[subj] = score_val
        else:
            student_input_data[subj] = 60 # Default score if subject is not found (e.g., average)

    # Fill interest scores
    for interest_col in trained_interests:
        interest_name = interest_col.replace('Interest_', '')
        student_input_data[interest_col] = student_interests_dict.get(interest_name, 3) # Default interest score of 3 if not specified

    # Convert to DataFrame for preprocessing
    student_df_for_pred = pd.DataFrame([student_input_data])

    # Reorder columns to match the training data's feature order
    # This is crucial for ColumnTransformer if it relies on column order (it does by default)
    student_df_for_pred = student_df_for_pred[trained_subjects + trained_interests]

    # 2. Preprocess the student's input data
    student_processed_features = preprocessor.transform(student_df_for_pred)

    # 3. Get career probabilities
    probabilities = model.predict_proba(student_processed_features)[0]

    # 4. Map probabilities to career labels
    career_probabilities = list(zip(model.classes_, probabilities))
    career_probabilities.sort(key=lambda x: x[1], reverse=True)

    # 5. Return top N recommendations with confidence
    recommendations = [(career, f"{prob*100:.2f}%") for career, prob in career_probabilities[:top_n]]

    return recommendations

"""## 9. Demo Cell

This cell runs the full pipeline end-to-end using the uploaded PDF, parsed data, and defined interests. It will print a nicely formatted final recommendation output.
"""

print("\n--- Running End-to-End Demo ---")

# Check if parsed_df exists and is not empty after potential synthetic data generation
# This check is crucial because pdf_filename might be true, but text extraction could still fail.
if 'parsed_df' in globals() and not parsed_df.empty:
    print(f"Student Name: {student_name}\n")
    print("Student's Parsed Subject Scores:")
    display(parsed_df)
    print("\nStudent's Stated Interests:")
    for interest, score in student_interests.items():
        print(f"- {interest}: {score}")

    print("\nGenerating career recommendations...")
    # Use the more robust Random Forest model for recommendations
    career_recommendations = recommend_career(parsed_df, student_interests, preprocessor, rf_model, top_n=3)

    print("\n### Top 3 Career Recommendations ###")
    for i, (career, confidence) in enumerate(career_recommendations):
        print(f"{i+1}. {career} (Confidence: {confidence})")
else:
    print("Cannot run demo. 'parsed_df' is not available or is empty. Please ensure a PDF was uploaded and successfully parsed, or that synthetic data was generated for demo.")

"""## 10. Notes/Limitations

This section explains the assumptions made in this implementation and outlines how the system can be improved or adapted with real-world data.

### Assumptions and Simplifications:

1.  **Synthetic Data**: The core limitation is the reliance on a synthetic dataset for model training. While efforts were made to introduce domain logic, it's an artificial representation. Real-world career recommendation systems require large, diverse, and representative datasets linking academic performance, skills, interests, and actual career outcomes.
2.  **PDF Parsing Robustness**: The regex and text extraction logic for PDF parsing is designed to handle common formats but might fail with highly irregular or image-based PDFs. A more advanced solution would involve OCR (Optical Character Recognition) for image-based PDFs and more sophisticated NLP (Natural Language Processing) techniques for information extraction.
3.  **Interest Quantification**: Student interests are captured via a simple dictionary with numerical scores. In a real system, this could be a more detailed questionnaire, psychometric assessment, or even extracted from text (e.g., essays, project descriptions).
4.  **Career Label Granularity**: The career paths defined (`Engineer`, `Doctor`, etc.) are high-level. A practical system might need more granular career categories.
5.  **Score Normalization**: For letter grades (A, B, C), a simple numerical conversion was used. A more nuanced approach would consider grading systems (e.g., GPA, weighted scores).
6.  **Static Feature Set**: The features (subjects, interests) are fixed. A dynamic system might incorporate extracurricular activities, skills, personality traits, etc.
7.  **Model Complexity**: While Decision Tree and Random Forest are good starting points, more complex models (e.g., gradient boosting, neural networks) could potentially capture more intricate relationships, given sufficient data.

### How to Replace with a Real Dataset:

To move from this prototype to a production-ready system, the primary step is to acquire and integrate a real dataset:

1.  **Data Collection**: Collect anonymized student data including:
    *   **Academic Records**: Subject-wise scores/grades, overall GPA.
    *   **Interests/Skills**: Data from student surveys, self-assessments, project participation.
    *   **Career Outcomes**: What careers students pursued after their studies, possibly linked with academic performance and interests.
2.  **Data Preprocessing**: Clean, normalize, and preprocess the real data. This might involve more complex handling of missing values, diverse grading systems, and text-based interest descriptions.
3.  **Feature Engineering Refinement**: Adapt the feature engineering steps to the real dataset's structure. This could include creating new features from existing ones (e.g., average science score, STEM vs. Humanities focus).
4.  **Model Retraining**: Retrain the chosen machine learning models (or experiment with new ones) on the real, preprocessed dataset.
5.  **Validation and Testing**: Thoroughly validate the model's performance on unseen real data, potentially using cross-validation and A/B testing in a live environment.
6.  **Iterative Improvement**: Continuously collect feedback and new data to refine the model and system over time.
"""