// Curated one-career-at-a-time pathway definitions mapping to master roadmap node IDs
// Configured with explicit col and row coordinates for clean, non-colliding layout matching the desired flow

export const CAREER_PATHWAYS_12TH = [
  {
    id: "tech_software_ai",
    title: "Software Engineer & AI Architect",
    stream: "Science PCM",
    icon: "💻",
    description: "From 12th PCM through JEE into B.Tech CSE / AI, or BCA into MCA, leading to Big Tech & AI Engineering.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_pcm", col: 1, row: 1 },
      // Upper branch: JEE -> B.Tech -> (PSU / M.Tech)
      { id: "exam_jee", col: 2, row: 0 },
      { id: "c_btech", col: 3, row: 0 },
      { id: "gov_psu", col: 4, row: -1 },
      { id: "pg_mtech", col: 4, row: 0.5 },
      // Lower branch: BCA -> MCA
      { id: "c_bca", col: 2, row: 2 },
      { id: "pg_mca", col: 3, row: 2 },
      // Converge: Tech Domain -> Software Engineer
      { id: "cg_tech", col: 5, row: 1.5 },
      { id: "career_tech_1", col: 6, row: 1.5, highlight: true },
    ],
    edges: [
      { source: "root_12th", target: "stream_pcm" },
      { source: "stream_pcm", target: "exam_jee" },
      { source: "stream_pcm", target: "c_bca" },
      { source: "exam_jee", target: "c_btech" },
      { source: "c_bca", target: "pg_mca" },
      { source: "c_btech", target: "gov_psu" },
      { source: "c_btech", target: "pg_mtech" },
      { source: "pg_mtech", target: "cg_tech" },
      { source: "pg_mca", target: "cg_tech" },
      { source: "cg_tech", target: "career_tech_1" },
    ],
  },
  {
    id: "medical_mbbs_doctor",
    title: "Medical Doctor & Specialist Surgeon",
    stream: "Science PCB",
    icon: "🩺",
    description: "Clinical pathway via NEET into MBBS followed by MD/MS specialization and Super-Speciality (DM/M.Ch).",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_pcb", col: 1, row: 1 },
      { id: "exam_neet", col: 2, row: 1 },
      { id: "c_mbbs", col: 3, row: 1 },
      { id: "pg_mdms", col: 4, row: 0.5 },
      { id: "pg_dm", col: 5, row: 0.5 },
      { id: "cg_medicine", col: 6, row: 1 },
      { id: "career_medicine_1", col: 7, row: 1, highlight: true },
      { id: "career_medicine_2", col: 7, row: 2 },
    ],
    edges: [
      { source: "root_12th", target: "stream_pcb" },
      { source: "stream_pcb", target: "exam_neet" },
      { source: "exam_neet", target: "c_mbbs" },
      { source: "c_mbbs", target: "pg_mdms" },
      { source: "pg_mdms", target: "pg_dm" },
      { source: "pg_dm", target: "cg_medicine" },
      { source: "cg_medicine", target: "career_medicine_1" },
      { source: "cg_medicine", target: "career_medicine_2" },
    ],
  },
  {
    id: "pharma_scientist",
    title: "Pharmacist & Pharmaceutical Scientist",
    stream: "Science PCB",
    icon: "💊",
    description: "Drug formulation, clinical trials, and pharmaceutical manufacturing through B.Pharm and M.Pharm.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_pcb", col: 1, row: 1 },
      { id: "c_bpharm", col: 2, row: 1 },
      { id: "pg_mpharm", col: 3, row: 1 },
      { id: "cg_pharma", col: 4, row: 1 },
      { id: "career_pharma_1", col: 5, row: 1, highlight: true },
      { id: "career_pharma_2", col: 5, row: 2 },
    ],
    edges: [
      { source: "root_12th", target: "stream_pcb" },
      { source: "stream_pcb", target: "c_bpharm" },
      { source: "c_bpharm", target: "pg_mpharm" },
      { source: "pg_mpharm", target: "cg_pharma" },
      { source: "cg_pharma", target: "career_pharma_1" },
      { source: "cg_pharma", target: "career_pharma_2" },
    ],
  },
  {
    id: "eng_core_mechanical_civil",
    title: "Core Engineering & PSU Specialist",
    stream: "Science PCM",
    icon: "⚙️",
    description: "Mechanical, Civil, and Electrical engineering leading to infrastructure, PSU Maharatnas, and DRDO/ISRO.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_pcm", col: 1, row: 1 },
      { id: "exam_jee", col: 2, row: 1 },
      { id: "c_btech", col: 3, row: 1 },
      { id: "gov_drdo", col: 4, row: -0.5 },
      { id: "gov_psu", col: 4, row: 0.5 },
      { id: "cg_engineering", col: 5, row: 1 },
      { id: "career_engineering_1", col: 6, row: 1, highlight: true },
      { id: "career_engineering_2", col: 6, row: 2 },
    ],
    edges: [
      { source: "root_12th", target: "stream_pcm" },
      { source: "stream_pcm", target: "exam_jee" },
      { source: "exam_jee", target: "c_btech" },
      { source: "c_btech", target: "gov_drdo" },
      { source: "c_btech", target: "gov_psu" },
      { source: "c_btech", target: "cg_engineering" },
      { source: "cg_engineering", target: "career_engineering_1" },
      { source: "cg_engineering", target: "career_engineering_2" },
    ],
  },
  {
    id: "finance_ca_auditor",
    title: "Chartered Accountant (CA) & Auditor",
    stream: "Commerce",
    icon: "📊",
    description: "Premier financial certification via ICAI Foundation, Intermediate, and Articleship to practicing Chartered Accountant.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_commerce", col: 1, row: 1 },
      // Upper branch: CA
      { id: "c_ca", col: 2, row: 0.5 },
      // Lower branch: B.Com (Hons)
      { id: "c_bcom_hons", col: 2, row: 2 },
      { id: "cg_finance", col: 3, row: 1 },
      { id: "career_finance_1", col: 4, row: 1, highlight: true },
      { id: "career_finance_2", col: 4, row: 2 },
    ],
    edges: [
      { source: "root_12th", target: "stream_commerce" },
      { source: "stream_commerce", target: "c_ca" },
      { source: "stream_commerce", target: "c_bcom_hons" },
      { source: "c_ca", target: "cg_finance" },
      { source: "c_bcom_hons", target: "cg_finance" },
      { source: "cg_finance", target: "career_finance_1" },
      { source: "cg_finance", target: "career_finance_2" },
    ],
  },
  {
    id: "business_mba_consultant",
    title: "Management Consultant & Business Leader",
    stream: "Commerce",
    icon: "💼",
    description: "Undergraduate degree in Business Management (BBA/BMS) followed by prestigious MBA at top IIMs/B-schools.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_commerce", col: 1, row: 1 },
      { id: "exam_cuet", col: 2, row: 1 },
      { id: "c_bba", col: 3, row: 1 },
      { id: "entrepreneurship", col: 4, row: 0 },
      { id: "pg_mba", col: 4, row: 1 },
      { id: "cg_business", col: 5, row: 1 },
      { id: "career_business_1", col: 6, row: 1, highlight: true },
    ],
    edges: [
      { source: "root_12th", target: "stream_commerce" },
      { source: "stream_commerce", target: "exam_cuet" },
      { source: "exam_cuet", target: "c_bba" },
      { source: "c_bba", target: "entrepreneurship" },
      { source: "c_bba", target: "pg_mba" },
      { source: "pg_mba", target: "cg_business" },
      { source: "cg_business", target: "career_business_1" },
    ],
  },
  {
    id: "law_corporate_advocate",
    title: "Corporate Legal Counsel & Advocate",
    stream: "Arts & Humanities",
    icon: "⚖️",
    description: "National Law Universities via CLAT into 5-Year Integrated BA LLB / BBA LLB, followed by Bar Council enrollment or LL.M.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_arts", col: 1, row: 1 },
      { id: "exam_clat", col: 2, row: 1 },
      { id: "c_law", col: 3, row: 1 },
      { id: "pg_llm", col: 4, row: 0.5 },
      { id: "cg_law", col: 5, row: 1 },
      { id: "career_law_1", col: 6, row: 1, highlight: true },
      { id: "career_law_2", col: 6, row: 2 },
    ],
    edges: [
      { source: "root_12th", target: "stream_arts" },
      { source: "stream_arts", target: "exam_clat" },
      { source: "exam_clat", target: "c_law" },
      { source: "c_law", target: "pg_llm" },
      { source: "pg_llm", target: "cg_law" },
      { source: "cg_law", target: "career_law_1" },
      { source: "cg_law", target: "career_law_2" },
    ],
  },
  {
    id: "civil_services_upsc",
    title: "Civil Services (IAS / IPS / IFS)",
    stream: "Open to Any Stream",
    icon: "🇮🇳",
    description: "Graduation in any stream followed by UPSC Civil Services Examination (CSE) for prestigious administrative leadership.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_any_stream", col: 1, row: 1 },
      { id: "c_ba", col: 2, row: 0.5 },
      { id: "c_bcom", col: 2, row: 2 },
      { id: "gov_upsc", col: 3, row: 1, highlight: true },
      { id: "gov_state_psc", col: 4, row: 1 },
    ],
    edges: [
      { source: "root_12th", target: "stream_any_stream" },
      { source: "stream_any_stream", target: "c_ba" },
      { source: "stream_any_stream", target: "c_bcom" },
      { source: "c_ba", target: "gov_upsc" },
      { source: "c_bcom", target: "gov_upsc" },
      { source: "gov_upsc", target: "gov_state_psc" },
    ],
  },
  {
    id: "design_product_ux",
    title: "Product & Industrial Designer",
    stream: "Arts & Humanities",
    icon: "🎨",
    description: "Design entrance (NID/UCEED) through B.Des and M.Des for digital product, UI/UX, and industrial design.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_arts", col: 1, row: 1 },
      { id: "c_bdes", col: 2, row: 1 },
      { id: "pg_mdes", col: 3, row: 1 },
      { id: "cg_design", col: 4, row: 1 },
      { id: "career_design_1", col: 5, row: 1, highlight: true },
      { id: "career_design_2", col: 5, row: 2 },
    ],
    edges: [
      { source: "root_12th", target: "stream_arts" },
      { source: "stream_arts", target: "c_bdes" },
      { source: "c_bdes", target: "pg_mdes" },
      { source: "pg_mdes", target: "cg_design" },
      { source: "cg_design", target: "career_design_1" },
      { source: "cg_design", target: "career_design_2" },
    ],
  },
  {
    id: "biotech_geneticist",
    title: "Biotechnologist & Research Scientist",
    stream: "Science PCMB",
    icon: "🧬",
    description: "Intersection of biology, computing, and technology in genetics, bio-informatics, and molecular therapeutics.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_pcmb", col: 1, row: 1 },
      { id: "c_biotech", col: 2, row: 1 },
      { id: "pg_mtech_biotech", col: 3, row: 1 },
      { id: "research_phd", col: 4, row: 1 },
      { id: "cg_life", col: 5, row: 1 },
      { id: "career_life_1", col: 6, row: 1, highlight: true },
    ],
    edges: [
      { source: "root_12th", target: "stream_pcmb" },
      { source: "stream_pcmb", target: "c_biotech" },
      { source: "c_biotech", target: "pg_mtech_biotech" },
      { source: "pg_mtech_biotech", target: "research_phd" },
      { source: "research_phd", target: "cg_life" },
      { source: "cg_life", target: "career_life_1" },
    ],
  },
  {
    id: "architecture_urban_planner",
    title: "Architect & Urban Planner",
    stream: "Science PCM",
    icon: "🏛️",
    description: "NATA/JEE Paper 2 entrance into 5-Year B.Arch followed by Council of Architecture registration and urban design.",
    nodes: [
      { id: "root_12th", col: 0, row: 1 },
      { id: "stream_pcm", col: 1, row: 1 },
      { id: "exam_nata", col: 2, row: 1 },
      { id: "c_barch", col: 3, row: 1 },
      { id: "pg_march", col: 4, row: 1 },
      { id: "cg_architecture", col: 5, row: 1 },
      { id: "career_architecture_1", col: 6, row: 1, highlight: true },
    ],
    edges: [
      { source: "root_12th", target: "stream_pcm" },
      { source: "stream_pcm", target: "exam_nata" },
      { source: "exam_nata", target: "c_barch" },
      { source: "c_barch", target: "pg_march" },
      { source: "pg_march", target: "cg_architecture" },
      { source: "cg_architecture", target: "career_architecture_1" },
    ],
  },
];

export const CAREER_PATHWAYS_10TH = [
  {
    id: "polytechnic_cse_btech",
    title: "Polytechnic Diploma in CSE ➔ B.Tech Lateral Entry",
    stream: "Polytechnic Diploma",
    icon: "💻",
    description: "Direct 3-year practical engineering diploma after Class 10 with direct lateral admission into 2nd Year B.Tech.",
    nodes: [
      { id: "root_10th", col: 0, row: 1 },
      { id: "a004_diploma", col: 1, row: 1 },
      { id: "dp_cse", col: 2, row: 1 },
      { id: "diploma_je", col: 3, row: 0 },
      { id: "diploma_gov", col: 4, row: 0 },
      { id: "btech_lateral", col: 3, row: 1 },
      { id: "career_software", col: 4, row: 1, highlight: true },
    ],
    edges: [
      { source: "root_10th", target: "a004_diploma" },
      { source: "a004_diploma", target: "dp_cse" },
      { source: "dp_cse", target: "diploma_je" },
      { source: "diploma_je", target: "diploma_gov" },
      { source: "dp_cse", target: "btech_lateral" },
      { source: "btech_lateral", target: "career_software" },
    ],
  },
  {
    id: "polytechnic_civil_mechanical",
    title: "Polytechnic Diploma in Civil / Mechanical ➔ Junior Engineer (JE)",
    stream: "Polytechnic Diploma",
    icon: "🏗️",
    description: "Hands-on engineering diploma qualifying for SSC JE, Railways RRB JE, State PWD, and industrial engineering.",
    nodes: [
      { id: "root_10th", col: 0, row: 1 },
      { id: "a004_diploma", col: 1, row: 1 },
      // Civil branch
      { id: "dp_civil", col: 2, row: 0.5 },
      { id: "diploma_je", col: 3, row: 0.5 },
      { id: "diploma_gov", col: 4, row: 0.5, highlight: true },
      // Mechanical branch
      { id: "dp_me", col: 2, row: 2 },
      { id: "btech_lateral", col: 3, row: 2 },
      { id: "career_engineer", col: 4, row: 2 },
    ],
    edges: [
      { source: "root_10th", target: "a004_diploma" },
      { source: "a004_diploma", target: "dp_civil" },
      { source: "dp_civil", target: "diploma_je" },
      { source: "diploma_je", target: "diploma_gov" },
      { source: "a004_diploma", target: "dp_me" },
      { source: "dp_me", target: "btech_lateral" },
      { source: "btech_lateral", target: "career_engineer" },
    ],
  },
  {
    id: "iti_electrician_railways",
    title: "ITI Electrician & Fitter ➔ PSU / Railways Technician",
    stream: "ITI & Vocational",
    icon: "⚡",
    description: "1-2 year technical trade certification with apprenticeship leading to direct recruitment in Indian Railways, PSUs, and power grids.",
    nodes: [
      { id: "root_10th", col: 0, row: 1 },
      { id: "a005_iti", col: 1, row: 1 },
      // Electrician route
      { id: "iti_electrician", col: 2, row: 0.5 },
      { id: "apprenticeship", col: 3, row: 0.5 },
      { id: "iti_gov", col: 4, row: 1, highlight: true },
      // Fitter route
      { id: "iti_fitter", col: 2, row: 2 },
      { id: "iti_employment", col: 3, row: 2 },
    ],
    edges: [
      { source: "root_10th", target: "a005_iti" },
      { source: "a005_iti", target: "iti_electrician" },
      { source: "iti_electrician", target: "apprenticeship" },
      { source: "apprenticeship", target: "iti_gov" },
      { source: "a005_iti", target: "iti_fitter" },
      { source: "iti_fitter", target: "iti_employment" },
    ],
  },
  {
    id: "iti_copa_office_it",
    title: "ITI COPA ➔ Computer Operator & Office IT Specialist",
    stream: "ITI & Vocational",
    icon: "🖥️",
    description: "Computer Operator and Programming Assistant trade for commercial data processing, IT support, and government office administration.",
    nodes: [
      { id: "root_10th", col: 0, row: 1 },
      { id: "a005_iti", col: 1, row: 1 },
      { id: "iti_copa", col: 2, row: 1 },
      { id: "skill_worker", col: 3, row: 1, highlight: true },
      { id: "v003_nielit", col: 2, row: 2 },
      { id: "nielit_it", col: 3, row: 2 },
    ],
    edges: [
      { source: "root_10th", target: "a005_iti" },
      { source: "a005_iti", target: "iti_copa" },
      { source: "iti_copa", target: "skill_worker" },
      { source: "root_10th", target: "v003_nielit" },
      { source: "v003_nielit", target: "nielit_it" },
    ],
  },
  {
    id: "science_pcm_academic",
    title: "10+2 Science (PCM) ➔ B.Tech / Computing Degrees",
    stream: "Science PCM",
    icon: "🔬",
    description: "Academic progression into Class 11-12 Physics, Chemistry, Math for engineering, architecture, and technology degrees.",
    nodes: [
      { id: "root_10th", col: 0, row: 1 },
      { id: "a001_pcm", col: 1, row: 1 },
      // BCA / Computing
      { id: "c_bca", col: 2, row: 0.5 },
      { id: "pg_mca", col: 3, row: 0.5 },
      { id: "career_software", col: 4, row: 1, highlight: true },
      // B.Sc CS / Engineering
      { id: "c_bsc_cs", col: 2, row: 2 },
      { id: "career_engineer", col: 3, row: 2 },
    ],
    edges: [
      { source: "root_10th", target: "a001_pcm" },
      { source: "a001_pcm", target: "c_bca" },
      { source: "c_bca", target: "pg_mca" },
      { source: "pg_mca", target: "career_software" },
      { source: "a001_pcm", target: "c_bsc_cs" },
      { source: "c_bsc_cs", target: "career_engineer" },
    ],
  },
  {
    id: "science_pcb_academic",
    title: "10+2 Science (PCB) ➔ Medical & Healthcare Degrees",
    stream: "Science PCB",
    icon: "🩺",
    description: "Academic progression into Physics, Chemistry, Biology for medical, dental, allied health, and pharmacy pathways.",
    nodes: [
      { id: "root_10th", col: 0, row: 1 },
      { id: "a001_pcb", col: 1, row: 1 },
      // MBBS
      { id: "c_mbbs", col: 2, row: 0.5 },
      { id: "career_doctor", col: 3, row: 0.5, highlight: true },
      // Pharmacy
      { id: "c_bpharm", col: 2, row: 2 },
      { id: "career_pharmacist", col: 3, row: 2 },
    ],
    edges: [
      { source: "root_10th", target: "a001_pcb" },
      { source: "a001_pcb", target: "c_mbbs" },
      { source: "c_mbbs", target: "career_doctor" },
      { source: "a001_pcb", target: "c_bpharm" },
      { source: "c_bpharm", target: "career_pharmacist" },
    ],
  },
  {
    id: "commerce_ca_finance",
    title: "10+2 Commerce ➔ B.Com / Chartered Accountancy",
    stream: "Commerce",
    icon: "📊",
    description: "Accountancy, Economics, Business Studies, and Mathematics leading to Chartered Accountancy, B.Com, and corporate banking.",
    nodes: [
      { id: "root_10th", col: 0, row: 1 },
      { id: "a002_com_math", col: 1, row: 1 },
      // CA path
      { id: "p_ca", col: 2, row: 0.5 },
      { id: "career_ca", col: 3, row: 0.5, highlight: true },
      // B.Com path
      { id: "c_bcom", col: 2, row: 2 },
      { id: "career_finance", col: 3, row: 2 },
    ],
    edges: [
      { source: "root_10th", target: "a002_com_math" },
      { source: "a002_com_math", target: "p_ca" },
      { source: "p_ca", target: "career_ca" },
      { source: "a002_com_math", target: "c_bcom" },
      { source: "c_bcom", target: "career_finance" },
    ],
  },
  {
    id: "arts_humanities_law_upsc",
    title: "10+2 Arts / Humanities ➔ 5-Year Law / Civil Services",
    stream: "Arts & Humanities",
    icon: "⚖️",
    description: "History, Political Science, Psychology, and Sociology leading to integrated Law (BA LLB) and Civil Services (UPSC).",
    nodes: [
      { id: "root_10th", col: 0, row: 1 },
      { id: "a003_arts", col: 1, row: 1 },
      // Law path
      { id: "c_llb5", col: 2, row: 0.5 },
      { id: "career_lawyer", col: 3, row: 0.5, highlight: true },
      // Civil Services path
      { id: "c_ba", col: 2, row: 2 },
      { id: "gov_upsc", col: 3, row: 2 },
    ],
    edges: [
      { source: "root_10th", target: "a003_arts" },
      { source: "a003_arts", target: "c_llb5" },
      { source: "c_llb5", target: "career_lawyer" },
      { source: "a003_arts", target: "c_ba" },
      { source: "c_ba", target: "gov_upsc" },
    ],
  },
];
